:PROPERTIES:
:ID: e74abe0f-9dcb-42f3-9912-95c1362d3443
:END:
#+TITLE: PDF to images with Poppler and pdftoppm

[[file:..][..]]

* PDF: a format for documents that others can read

What if there was a portable document format we could use to share our slides---without assuming that the consumer of our slides has a Google account, a Microsoft Office license or a Mac with Keynote installed?

Enter Portable Document Format.
Or PDF, as we often say day to day.

The [[https://en.wikipedia.org/wiki/PDF][PDF format]] was originally developed by Adobe, but became an [[https://en.wikipedia.org/wiki/International_Organization_for_Standardization][ISO]] standard in 2008.
Today, most web browsers have excellent support for viewing PDFs, and operating systems often provide a good PDF reader out of the box.

For both [[id:26776cc4-e64d-494b-b24c-784b2c57866d][Build Your Own Little Memex with Babashka]] and [[id:436d7df4-f986-4bff-8efa-44bf72099859][Lessons learned teaching Elm to kids]], I chose to write my slides in a format suited to /produce content/, export to PDF and show the PDF on the talk from a very boring PDF reader such as Firefox.

But once in a while, a question arises: can I please provide a version in PowerPoint?
Or perhaps in Google Slides?

* Export from PDF with Pandoc?

I've tried using [[id:8ebac1d6-a7e8-4556-a483-a1b1c11f832d][Pandoc]] to convert the PDF to a different slideshow format directly, but I haven't loved the experience.
I get a new file, sure.
But it might not be the way I want.

* Export from PDF with Poppler 🤗

A different option is to convert the PDF to a set of images, then copy each image into the slideshow.
Plenty of tools can do this.
[[https://poppler.freedesktop.org/][Poppler]] is one.

Poppler is an open source project for working with PDFs.
You can probably install it with your favourite package manager.

Now, you can produce your images:

#+begin_src shell
# First, install Poppler.
# After a successful Poppler installation, you should get a binary called `pdftoppm`.
$ which pdftoppm

# Then you need some slides.
# Bring your own, or take some of mine.
$ wget https://www.teodorheggelund.com/static/teaching-kids-elm.pdf

# Then convert to images!
$ mkdir slides
$ pdftoppm -jpeg -r 600 teaching-kids-elm.pdf slides/slide
#+end_src

Above, I chose some options to ensure a smooth import into Google Slides.

- =-jpeg= :: images are JPEGs
- =-r 600= :: image resolution is 600 points per image (good enough quality for my usage)
- =teaching-kids-elm.pdf= :: the input PDF
- =slides/slide= :: is the image path prefix.
  One resulting image is =slides/slide-21.jpg=

Finally, do what you want with the images!
