:PROPERTIES:
:ID: 224c548c-b444-4557-86a5-9056a393548f
:END:
#+TITLE: Teknologi for 친 bygge produkt --- en introduksjon

[[file:..][..]]

(basert p친 [[https://roamresearch.com/#/app/teod/page/X3CSJVLdw][Teodors notater]], men notatene er ikke offentlig)

Hvordan bruker vi teknologi til 친 bygge produkt?
Det sp칮rsm친let har jeg brukt mye tid p친 de siste fire 친rene.
Her er mitt perspektiv.

Vi skal dekke tre problemer:

- B칮r jeg sette meg ned og kode eller grave i problemene vi l칮ser n친?
- Hvordan jobber vi sammen p친 gode produktteam?
- Hvordan b칮r jeg be om hjelp?

Vi skal plukke hver av problemen fra hverandre ved 친:

- Definere problemet
- Beskrive symptomer p친 problemet---hvordan vet vi at vi har problemet?
- Beskrive utfordringer---kanksje det ikke finnes en oppskrift som /l칮ser/ problemet.
- Beskrive handlingsrommet v친rt: hva kan vi gj칮re n친r vi har problemet?

* B칮r jeg sette meg ned og kode eller grave i problemene vi l칮ser n친?

*Hva er problemet?*
Det er dumt 친 bruke masse tid p친 친 l칮se feil problem, og det kan v칝re skikkelig givende 친 se ekte folk bruke det du har laget til 친 l칮se ekte problemer.
Samtidig er teknologi vanskelig nok i seg selv---det krever mye innsats 친 bli en solid utvikler.
S친 hva b칮r vi fokusere p친?
Kun kode? Kun produkt? Litt av hvert?

*Diagnose.*
Du har begrenset tid.
Det er dumt 친 lage noe som ingen kommer til 친 bruke.
Samtidig er det dumt 친 ikke f친 brukt det du faktisk er god p친 etter en (snart fullf칮rt) universitetsgrad!

*Utfordringer.*
Her finnes det ikke noe 100%-svar.
Hvis du fortsetter 친 l칝re, b친de p친 tech- og produkt-biten kommer du til 친 f친 en bedre og bedre magef칮lelse.
Tech og produkt er hver for seg store fagfelt som tar lang tid 친 mestre.

*Handlingsrom.*
Hva kan du gj칮re?
Her er tre forslag.

1. /Ta stilling til bruken av det du lager/.
   Hvem bruker det?
   I hvilken situasjon?
   Til 친 oppn친 hvilket m친l?
   hvis du ikke kjenner bruken av det du lager, vet du ikke om det til syvende og sist er verdifullt.
2. /Det er lurt 친 l칝re seg 친 jobbe med egen kode i prod/.
   Inntill ekte folk bruker det du har laget, er det enkelte lekser du aldri l칝rer deg.
   Plutselig dukker det opp problemer som tar to uker lenger enn du skulle trodd.
   Jeg er glad i 친 starte med noe ekte, og f친 det ut, hele veien p친 nett.
3. Innovasjon Norge anbefaler en balanse mellom [[id:add61309-25d3-418d-8a9b-542915198e53][Technology Readiness Level]] (TRL) og [[id:990561a0-48e8-4a32-a225-41650ea8edda][Business Readiness Level]] (BRL).
   Jeg synes denne inndelingen er en god beskrivelse av god produktutvikling.
   Leser du den, kommer du ogs친 ett steg n칝rmere 친 skrive en god Innovasjon Norge-s칮knad.
   Ta en titt p친 tabellene, og pr칮v 친 si noe om prosjektet ditt.
   Hva er TRL (1-9)?
   Hva er BRL (1-9)?

* Hvordan jobber vi sammen p친 gode produktteam?

*Hva er problemet?*
"Bare gj칮r ting som lager verdi" er et ikkesvar.
Hva er veien fra koden din til folk som betaler for 친 f친 bruke koden din til 친 l칮se problemer de bryr seg om i praksis?
Den veien g친r (nesten) alltid gjennom 친 /jobbe med folk/.
Folk p친 teamet ditt.
Folk som kan hjelpe deg i Iterate.
Kunder, partnere, investorer.
I din relasjon med alle disse menneskene er det ting du kan /gj칮re/ for at dere kan forst친 hverandre bedre, og for 친 gj칮re det lett for dere 친 hjelpe hverandre.

*Diagnose*.
I din relasjon til en person X:

- Stoler X p친 deg? Stoler du p친 X?
- Skj칮nner X hva du synes er bra? Skj칮nner du hva X synes er bra?
- Skj칮nner X hva du pr칮ver 친 oppn친? Skj칮nner du hva X pr칮ver 친 oppn친?

*Utfordringer.*
Disse greien er vanskelig!
Hva om:

"Jeg er usikker p친 hva vi pr칮ver 친 oppn친."
Ja.
Det krever trening 친 bli god til 친 sette m친l.
Be folk som kan det du lurer p친 om hjelp. Vi er her for 친 hjelpe deg.

"Jeg vet ikke hva "bra" betyr her. Hva er god markedsf칮ring? Hva er godt design?"
Ja.
Det krever trening 친 f친 en forst친else av kvalitet innen fagfeltet du driver med, enten du pr칮ver 친 skrive overbevisende tekst p친 landingssiden, lage et godt design, eller pr칮ver 친 f친 folk til 친 kj칮pe det du har laget.
Men du kan be folk som kan det du lurer p친 om hjelp!
Vi er her for 친 hjelpe deg.
游뗵

*Handlingsrom*.
N친r du ikke vet akkurat hva du b칮r gj칮re, kan du bygge sterkere relasjoner med menneskene du har rundt deg.

- /tillit/ --- hva kan du gj칮re for at personen stoler p친 deg?
- /delt forst친else av kvalitet/ --- hva synes personen er /bra/ i sin hverdag?
  Hva er d친rlig?
- /delt forst친else av intensjon/ --- hvilke m친l pr칮ver personen 친 oppn친?

Disse tre er ekstremt viktige n친r du jobber med kunder eller potensielle kunder
Hvis kunden ikke stoler p친 deg, vil ikke kunden v칝re 칝rlig med deg.
Hvis du ikke skj칮nner hva kunden synes er bra, klarer du verken levere bra ting, eller forst친 /hva/ du kan gj칮re for 친 levere bra ting.
Hvis du ikke forst친r hva kunden pr칮ver 친 oppn친 fra dag til dag, klarer du ikke 친 lage et produkt som er bra nok til at kunden vil kj칮pe.

*Referanser.*
[[id:45f5cc28-79f9-4a88-930f-06f77e727479][Marty Cagan]] skriver sv칝rt godt om hvordan gode produktteam jobber i praksis.
Start med [[id:022060d8-811e-41dd-9c59-f179945a2dbc][Inspired]], og g친 videre p친 [[id:4c96fb35-ee33-4386-b2b8-f7b80cd5d8a5][Empowered]].

For 친 bygge tillit kan du starte med 친 ta eierskap til problemer.
Her liker jeg [[id:40f7d350-4adb-4a1c-bee8-70b38e8006c0][Extreme Ownership]] av [[id:5dce2cbf-71b0-4038-ad1d-7174236fd964][Jocko Willink]].

* Hvordan b칮r jeg be om hjelp?

*Hva er problemet?*
"Bare be om hjelp" er et ikke-svar.
Hvem b칮r jeg be om hjelp?
Hva b칮r jeg be om hjelp til?
Hvor mye hjelp b칮r jeg be om?
Hvor mye innsats b칮r jeg legge ned selv f칮r jeg ber om hjelp?

*Diagnose.*
Du st친r fast, og vet ikke hva du skal gj칮re.

*Utfordringer.*
Selvinnsikt og intellektuell ydmykhet er sv칝rt viktige kvaliteter 친 ha hvis du vil bygge produkt---men de tar ogs친 tid 친 kultivere.

*Handlingsrom.*
Du kan sp칮rre hvem som kan hjelpe til p친 et problem.
Finn og jeg har en viss oversikt over hvem som kan hva i organisasjonen.

Hvis du klarer 친 skrive en konsis beskrivelse av problemet du trenger hjelp til, er det mye lettere 친 vite hvordan vi kan hjelpe deg.
칄n setning, kanskje to.

*Referanser.*
[[id:a3ce5686-05e5-4620-8d38-77af80203184][Trillion Dollar Coach]] er en fantastisk bok om 친 be om hjelp gjennom vinkelen /coaching/ og /[[id:5fd923f9-dc43-4a82-ac59-8785e98bc901][coachability]]/.
Boka handler om hvordan [[id:1430e8a9-2e4b-499e-9447-84c71985aaf1][Bill Campbell]] hjalp blant andre Steve Jobs med 친 styre Apple.
Jeg har ogs친 skrevet en annen tekst om hvordan 친 be om hjelp: [[id:55261ada-7ca6-4c94-88f5-446a9b35e5c4][How to ask experts for help]].
Cirka to minutter 친 lese, p친 engelsk.
