#+title: Iterate knowledge garden

[[./..][..]]

* Innhold fra andre folk
- Kent beck: https://geekincentives.substack.com/?utm_source=account-card&utm_content=reads
* 2022-06-30
Yo!

Jeg og @rune har en kontinuerlig g친ende diskusjon p친 om det er lurt 친 skrive ned kunnskap.

Hvorfor skrive ned kunnskap? Fordi det letter kommunikasjon.
Hvorfor ikke skrive ned kunskap? Fordi kunnskap kalsifiseres, blir til stein, s친 har vi prosesser som ingen vet hvorfor vi har, og hverdagen er dritt.

Jeg synes vi b칮r skrive ned ting.

Da er det viktig at strukturen er l칮st koblet og lenket, heller enn sentralisert / hierarkisk. Hva b칮r vi da bruke? Vi trenger dokumenter. Vi trenger lenker mellom dokumenter. Og vi trenger et format som alltid er lett 친 lese. Finnes det noe s친nt? Jepp - Internett!

HVA ER NESTE STEG?

Prosessen som funker for meg er "gradvis kuratering av notater og ideer til evergreen notes" (Andy Matuschak om Evergreen Notes). Jeg har begynt selv p친 https://play.teod.eu/ (alt er veldig work-in-progress)

HVA ER NESTE STEG???

游땐
Samler du kunnskap p친 nett? Jeg vil ha link :smile: (@oddmunds, hadde du en blogg? @anders, du har ogs친 noen greier p친 Medium, tror jeg?)
Er du interessert? Meld interesse i tr친d :point_right:
Har du kommentarer? Diskuter her p친 Slack! For min del hvorsomhelst. Jeg f칮lger med p친 #teodor-play.

#+begin_verse




















#+end_verse
