:PROPERTIES:
:ID: 7b5e0aae-f0f3-4efa-9966-ed79484eb86a
:END:
#+TITLE: Holding one's ideas so tightly they suffocate

[[file:..][..]]

Are words meant to be taken seriously?
Or not?

Are words fact?
Or are words meant to move the world?

Conversations die.
At times due to natural causes.
They lived a good life, and it was time to go home.

Other times they are killed by words.
Rather than explore together, we stop our partner in their track, making them hesitate.

Is that any good?

I value precision.
I value taking oneself and others seriously.
I want to cooperate with powerful individuals.

Yet; a certain "definiteness" can be heavier than precise.
The receiver may not be able to carry the weight.
Then, the receiver may not respond.

Words can be invitations to explore.
Words can start adventures.
Rather than suffocate our ideas, we can let them wander.

But ... is this only a dream?
Can we do this together, in practice?
Frankly, I'm not sure.
Perhaps ideas /will/ and /must/ suffocate until we trust and understand each other.

🤔

In that case, is cooperation a learned skill?
Something we must practice and re-learn every time we meet someone new?
Not by finding a box that fits everyone, but by letting people live outside of boxes?
Otherwise, why will they enjoy it?
