#+TITLE: in purrsuit
#+begin_verse
find your purrsuit.
  let play and intent be your perspective on life.
science is great explanations.
reduce clutter.
reduce noise.
spread knowledge.
it's good, i promise!

art is experience, shared.
beauty gives joy.
don't make it too good, too wise,
  if you do, you will not finish, not publish.
    publish gives more joy.
learn to respect your taste
  then cherish it, take it seriously
  then watch it evolve

don't take everything too seriously
it's no fun that way
what's more fun?
  the hubris of your ego.
  have you considered tossing it around?
  poking at it, for fun?
  your hubris, your pride.
  let yourself have hubris, have pride.
    then consider how silly it all is.
    then shower yourself in its flowery hubris.
      then move in and out of the pouring water.

don't go all the way alone.
movement alone is required
  to some extent
but experience is richer together.
  find someone to move with.
  move in formation.
  or move in chaotic joy.
    then enjoy.
#+end_verse
