:PROPERTIES:
:ID: 9f52d562-4a06-4ea1-a461-2018fca5baf1
:END:
#+TITLE: There's always a deliverable

[[file:..][..]]

#+begin_quote
Sorry, this article is totally incomplete.
Please bug me if you're interested in actually reading an ending.

I'm interested in the topic, but I'm not yet sure /why/.
The idea is that to formulate a deliverable (outcome) for your effort is good for you over the long term.

See also [[id:842f9b9a-de98-4187-863e-3e6cf1b1814d][What's a good intersection between work and play?]].

— Teodor 2022-09-21
#+end_quote

In tactical work, there's a deliverable.
In strategic work, there's a deliverable.

Just because realized end user value is further away, that doesn't mean we can't deliver something specific.
We just have to define our impact in terms of an intermediate goal, not the end state.

Strong values make intermediate goals easier.
With strong values, simply staying true to your values is a goal in itself.

First, the default --- write journal. Something like [[id:bd776ab0-d687-4f16-b66d-d03c86de2a2e][My public journal]].

/what do I want to put in this article?/

Idea: apply [[id:c8131839-be8d-4ca8-8bc3-eac72cfade15][Capability, feature and assembly]] to knowledge work.
A capability is a mental model, a definition.
A utility (feature) provides value in a context.
As a text, it motivates /why/. (see [[id:93ea907e-9dcb-4c6b-af7d-d9bc22c34d57][Aphorisms]], number 5).
An assembly solves for /discovery/.
How can I know what's available?
Where do I start?
