:PROPERTIES:
:ID: 3535df8d-0fb3-40b7-ada4-347339284151
:END:
#+TITLE: Becoming Empire

[[file:..][..]]

The rebels won.
Now what?

There is no longer a big, bad empire.
There is us—we are empire.
Things will change.
The pace will slow.
We will introduce bureaucracy.

Peace is here.
We no longer have to worry about food and shelter.
Those are provided.
We are slower than we used to be.
But the things we make now is built to last longer.
No temporary garages, we now build in concrete and steel.
We are building our legacy.

Our culture is taking hold.
Our people and our organization is part of that culture.
But also our history.

As we are proud of our history, we will strive to do work such that future generations can be proud of their history.
We are building our legacy.

-----

Calm is nice.
But we are starting to get bored.
Why are we no longer as fast as we were in the beginning?
Why can we no longer build with the same speed?

At this point, we realize that both speed and stability is possible, at the same time.
We can move the quickest when we move on a stable foundation.
