#+title: Playground - dump

* 2022-05-26
** From #teodor-discuss (Iterate slack)
Source: https://garasjen.slack.com/archives/C01KB5RSAU9/p1653562307600869

Hva vil jeg egentlig å få ut av en nettside?

Effektivt å skrive tekst. Kan gjøre det i vanlige tekstformater.
Frittstående sider. Løs kobling, trenger ikke samme struktur overalt.
Gjenbrukbare komponenter.
Hele greia funker som en statisk side.
Statisk html er sjekket inn i git.
Lynraske bygg.
Effektivt å jobbe med hiccup.

Effektivt å jobbe med ideer.
Effektivt å lenke mellom ideer.

Lett å få inn ting jeg har tegnet. Feks på papir, remarkable eller i figma

Twitter... Trenger jeg å tenke på det?
Kommentarer. Webmentions? Systemet jeg bruker i dag? Hacker news? Twitter?
Jeg ønsker jo å kunne diskutere ting på Twitter
Og det gir mening å ha invitasjoner til diskusjon på Twitter, samt invitasjon til å diskutere på Twitter på nettsiden.

Hva med unicad og blogging og artikler for sånt?

Approach: embed unicad I noe annet.
Approach: bygg skriving rett inn i unicad.
:thinking_face:

Hva får jeg egentlig ut av en nettside som jeg ikke får her i #teodor-discuss?
Tilgjengelig for folk utenfra
Bedre på å redigere store ting
Mer kontroll på presentasjon (også mer jobb)

Oddmund:
Har du vurdert å bare skrive nettsida di i HTML?

Det er jo cirka det jeg gjør på subcons.teod.eu. Bare via hiccup

Kan laste opp rå html også, og det funker fint.

Ting jeg ønsker å skrive om:
Ortogonalitet
Feedback-loop + API-design + hvordan ting funker
Eksempler på bruk av watchexec
Noe dataviz

@oddmunds jeg har prøvd å skrive html direkte, men det føles som å gå i gjørme. Med hiccup har jeg i alle fall en skikkelig editor. Men jeg liker bedre å redigere tekst i gode formater for tekst (feks org-mode, eller markdown, til en viss grad)

Enda en side:
Konvertering mellom Roam / html / hiccup / org-mode
Litt usikker på om jeg får til det rett i browser. Trenger kanskje en tjeneste. En backend. Med pandoc og Clojure bør det ikke være alt for vanskelig.
Men hvis jeg får opp noe sånt, kan jeg lett gå mellom formater.

Enda en side:
Signaler, starting av prosesser, stopping av prosesser. Sigterm, sigkill, sighup (?)
Kan lage en side i stedet for å lage presentasjon eller noe annet.
** Principles collected
*** Effektivt å skrive tekst. Kan gjøre det i vanlige tekstformater.
*** Frittstående sider. Løs kobling, trenger ikke samme struktur overalt.
*** Gjenbrukbare komponenter.
*** Hele greia funker som en statisk side.
*** Statisk html er sjekket inn i git.
*** Lynraske bygg.
*** Effektivt å jobbe med hiccup.
*** Effektivt å jobbe med ideer.
*** Effektivt å lenke mellom ideer.
*** (Kanskje) mulig å bruke sammen med Clerk.
** RANT
Man, I hate Mac stealing cmd+h. I want it to move stuff left in a hierarchy. But
mac steals it to hide windows.
** Outline collected
*** Ortogonalitet
*** Feedback-loop + API-design + hvordan ting funker
*** Eksempler på bruk av watchexec
*** Unix-terminalen gir deg superkrefter
relatert til ortogonalitet
relatert til watchexec
relatert til signaler, starting av prosesser, stopping av prosesser, sigterm,
sigkill, sighub
*** Noe dataviz
*** Konvertering mellom Roam / hiccup / html / org-mode
*** Signaler, starting av prosesser, stopping av prosesser. Sigterm, sigkill, sighup (?)
**** Kartlegging av interesse 2022-05-13
Kilde: https://garasjen.slack.com/archives/C2K35RDNJ/p1652440860308049

Likes: :raised_hands: * 5
***** Pitch
Idé til fagopplegg - graceful startup, graceful shutdown.
Forklare signaler (SIGTERM, SIGKILL, …), håndtering av signaler, reagere på Ctrl+C. Eventuelt også liveness og readiness i Kubernetes.
Hvis det hadde blitt arrangert noe sånt, ville du deltatt? (edited)
***** Kommentarer
Eilef - oh yes please!
Henrik - kill -9 <pid>
*** Innovasjon - som forstått gjennom bundling og unbundling
eksempler på bundling
eksempler på unbundling

verdi - arbeidsflyter
verktøy - prismodeller

ortogonalitet
** See also - curated links
I hate pure URLs without context. But ideas are meant to be understood in
context! So what's the context? "Where can we go from here"? I want the
relationships to be rich; a way of navigating in itself. An interaction mode, if
you will.
** Domains?
Ideally, I want to use cloudflare pages for this. I'd like to use Cloudflare
pages.

Buuut

That requires some major changes, some changes that might break my email setup.
So those are a bit dangerous, for now.

Options:

1. Slowly move to Cloudflare for teod.eu - but don't do anything too rash to
   early.
2. Just move over and see what happens, check whether mail breaks down or not.
3. Don't do it. Just keep the existing stuff.

If I just move over, what's the worst thing that can happen? I can (I think)
revert all changes I might be making.
