#+title: Intent

Aim your intent - explore - refactor towards orthogonality

**Hva er forskjellen p친 wip.org og intent.org?**

|        | intent.org             | wip.org                                  |
|--------+------------------------+------------------------------------------|
| Format | tempor칝r braindump     | liste av ting 친 l칝re og ting 친 skrive om |
| Form친l | f칮rste touch / capture | andre touch / curation / categorization  |

* 2022-05-27
** remix culture, the internet
knowledge garden

Iterate Knowledge Garden

Iterate Garden

Iterate Knowledge Playground

* 2022-06-12
** Feeling the need for opt-in structure
Right now, I have multilpe separate files & folders - each separate, living on
its own.

I'm feeling that the need for playground.edn has come.

Why?

Specifically - it could deliver a title for the main index. And I could separate
drafts and incomplete work from other stuff.
** If I was going to publish a Clerk document, how would I do it?
Ideas:

1. make all of this a clojure project
2. create a clojure project for clerk notebooks in a subdirectory - then copy
   the files out on demand
   1. Could perhaps have placeholder =playground.edn= files that point to the source
   2. Or =notebooks/= could mirror "/" - so that =notebooks/pendulum.clj= is
      compiled into =pendulum/index.html=.
   3. 游뱂
** Good architecture
1. Good namespace design
2. Not more indirection than necessary
3. Orthogonal capabilities

Would be interesting to compare this to Zach Tellman's book.

https://elementsofclojure.com/

#+begin_quote
The first chapter, Names, explains why names define the structure of our software, and how to judge whether a name is any good.

The second chapter, Idioms, provides specific, syntactic advice for writing Clojure which is clean and readable.

The third chapter, Indirection, looks at how code can be made simpler and more robust through separation.

The final chapter, Composition, explores how the constituent pieces of our code can be combined into an effective whole.
#+end_quote
