:PROPERTIES:
:ID: ca309c39-2c66-49bf-a674-f5f4c022b844
:END:
#+TITLE: Discovery, Power, Asymmetry

[[file:..][..]]

I believe in distributing and reifying intent.
Yet, during discovery there are asymmetries in experience, intent and context.
People are not equal.

Then what?

Oh, I think I know.

1. Treat people fairly
2. Don't assume people know, build shared understanding
3. Say no when required.

Perhaps it's that easy :)

-----

I expected this to be hard to impossible.
But respect for the self, the work and others seems to just ... solve it?

Also, don't get mad.
Getting mad doesn't help.

-----

Then ... how do we enable others to push intent back?

I think I know that one too :)
Do discovery in a system everyone can explore.

1. Everyone can contribute
2. Everyone can read anything

But:

1. Don't break ownership.
   Don't rewrite other people's ideas.
   Rather, build on them.
   Make your own.

So ... how do we get this into the blood, tears and daily habits of real people?
We simply ... do.
We use it as a medium for communication.
Lead by example!
Prototype in it!!

Sidenote: I'm enjoying the new Pandoc style.
There's more trailing whitespace than before.
Meaning I don't normally need to add my own trailing lines.
