#+title: play.teod.eu rolling retrospective

[[./..][..]]

Companion to play.teod.eu journal.

| play.teod.eu journal               | temporal, dump-oriented. |
| play.teod.eu rolling retrospective | topic-oriented           |

* should this page simply be called "meta"?
No.
"Meta" is never narrow.
Go for a single global layer, please.

* I need to "contract" / "narrow" before publishing

The stuff that's published on my site right now is a real mess.
Mess how?
In many ways.
But the big one: the ideas are intertwined.
There's coupling.
I could remove that coupling.
Or at least attempt to remove that coupling.

* Date tagging

I want metadata for :changed and :created.
First because I want to filter / sort.
Then perhaps later because that metadata is nice to have.

* play.teod.eu is just some code that generates some HTML

Not more.
There's a single indirection boundary.
Information as written --- indirection --- published HTML.
And that indirection is encoded in the CLI/Makefile --- not in opaque CI.

* comment system
Option: Comments on Twitter.
Option: Comments on Hacker News.
Option: Comments embedded straight into the text - via Github pull requests.
