:PROPERTIES:
:ID: 7cfe7fb2-c4c4-4ace-80a0-58c7883c19e7
:END:
#+TITLE: Do you dare be the judge of quality?

[[file:..][..]]

DRAFT

Want to absolutely destroy your working relationship with someone?
In an offhand remark, tell them that something they are proud of sucks.

I enjoy working with great people in order to build great things.
Most things aren't great.
We can follow Stephane Hessel or Cave Johnson and get mad.
When life gives you lemons, don't make lemonade.
Demand to see life's manager!
You don't want those damn lemons!

Or we can stop caring.
Everything is meaningless after all, right, so why care?
Taking responsibility is meaningless, just give up.

I want something different from anger and apathy.
I want something constructive.
Something that builds [[id:587fd857-1f93-4b59-935a-7681e5129665][trust, shared sense of quality and shared intent]].

I believe we /can/ talk constructively about quality, and that the solution is in narrow statements and indirect judgment.
What does that mean?
It's easier to describe it's negative rule.

/don't lie about quality/.

When you think something is bad but aren't quite sure, keep your absolute judgment to yourself.
And when you are sure it's time, be narrow in your judgment.
Err on the side of being too narrow.
Being too narrow in your criticism does not cause harm!
# Fjerner disse for nå.
#
#   Be precise about the problem you perceive.
#   Or provide an explicit example of something bad that might happen downstream from the bad choice.

Do you dare be the judge of quality?
Ask yourself twice before you act.
