stuff: scittle-buttons/index.html
	(cd .. && make)

scittle-buttons/index.html: scittle-buttons/index.org
	pandoc --standalone --from=org+smart scittle-buttons/index.org -o scittle-buttons/index.html
