:PROPERTIES:
:ID: 9dfae94f-677a-49a6-bee3-98a2bb470e48
:END:
#+title: Open problems

[[./..][..]]

Structure --- by idea, not by time.

List of problems I want to grapple with.

* Working properly with strategic initiatives
Ever since I went into IT in 2019, I've felt shackled by the time horizon of the teams I've been working with.
Where is the long term thinking?
For Unicad, it's vital that we're able to work with what matters long term.
Research is a better analogy for much of what we do than "coding stuff".

See also: https://cutlefish.substack.com/p/tbm-3052-why-do-we-have-no-strategy

See also: [[id:b94ada99-dfc3-4f3e-ba69-a4edf5fc1efd][Why don't we have a strategy?]]
* Getting cross-article Org-roam links working
I honestly cannot be bothered to maintain links to specific article IDs.
Especially before I've shared them for public consumption.
Meaning "Ready for comments" and above.
* C, OpenGL
What?
Problem?
Are C and OpenGL problems?

Well, not really.
But there's stuff here I want to learn.

What  specifically?

1. I want to be able to write code that uses the memory effectively.
   For that, I believe minimal distance between me and the memory is the way to go.
   So go C!
2. I want to understand how to think about memory layouts.
   What does it feel like when there's just me, the computer and its memory?
3. I want to be able to draw high-performance graphics!
4. I want to be able to write high-performance code.
