:PROPERTIES:
:ID: b8e8b0e5-0f49-4eee-a338-6265176ebfdc
:END:
#+TITLE: tensor calculus 101

[[file:..][..]]

Explanation from [[id:76e53c23-5a32-4e9e-b735-426fbc9f6982][Colin Smith]] that finally made it click for me, extracted from Slack:

#+begin_quote
I think sam may have slammed harder into tensor-land than necessary for this introduction. My entry point for this is: an up tuple is a vector just like in high school physics class. A down tuple is a linear functional, a function that wants to eat an up tuple and produce a real number. The word “functional” is just mathematical jargon for a function “from vectors to the field of their entries, i.e., real numbers” and linear here means that the functional must be linear in its argument, i.e, that you can distribute it over + and pull constants out

The reason the derivative produces a down tuple is that it needs to know what direction you want to go before it can provide you with an estimate of how much the differentiated function will change if you move slightly in that direction…i.e., it wants to eat an  up tuple and produce a real number. Since differentiation is linear at its core, it produces a linear functional.
#+end_quote

My summary:

#+begin_quote
1. up tuples are the vectors I'm used to
2. In order to find a sensible way to define =D=, we need some way to extract which derivative we're interested in.
   Down tuples give you that.
#+end_quote

Colin continues:

#+begin_quote
It took me a long time to get comfortable with this idea, and really, it was SICM that helped me really get it. If you pick up almost any physics book, they will kill your brain with “it’s up or down depending on whether it ‘transforms’ with or against some coordinate transformation you want to apply” but that is not helpful. Other physics texts (even Goldstein does this) just decide that it’s too much bother to introduce the up/down distinction and all indices are down and the distinction is swept under th rug. Linear algebra textbooks call the space of linear functionals the “dual space” of the original vector space but don’t mention the derivative since they don’t want icky real analysis to puncture their axiomatic reasoning class, depriving the student of the one central example that might have motivated the entire thing….
#+end_quote

#+begin_quote
and then the linear algebra textbook goes on to show that the dual space is isomorphic to the original vector space, leaving you wondering why the whole idea was introduced.
#+end_quote

questions:

1. what is the metric tensor?
