:PROPERTIES:
:ID: b94ada99-dfc3-4f3e-ba69-a4edf5fc1efd
:END:
#+TITLE: Why don't we have a strategy?

[[./..][..]]

Commentary on /Why Don't We Have a Strategy?/ by John Cutler.
Reading the [[https://cutlefish.substack.com/p/tbm-3052-why-do-we-have-no-strategy][original article on The Beautiful Mess]] is probably a good idea.

Note from 2022-09-25: this is really an enriched remote reference.
Remote reference with commentary.
Canonical source is somewhere else.
Remixing here.
I want the structure of play.teod.eu to reflect that.
But I don't know how yet.

* "The system is not built for me to think. The system is built for me to be reactionary"
#+begin_quote
A product leader recently told me: "The system is not built for me to think. The
system is built for me to be reactionary." Why? The theory goes that ideas are
cheap, and execution is everything. We celebrate productivity, output, and
achieving goals. Consider all the rituals teams have around managing output,
tracking metrics, forecasting, sharing plans, and boosting productivity.
#+end_quote

I agree, so much.
When ideas are cheap and execution expensive, we value execution over everything else.
And the people working with ideas are ... tossed around, in a sense.
"WHAT?"
"Why can't you describe what you worked on yesterday???"
It's kind of hard to reduce to a three sentence summary.
"Are you lazy or what???"
It feels like we're lost in specificity.

Trust.
Do we trust ourselves to have good ideas?
Do we trust others to have even better ideas?

Perhaps 50/50 /must/ be the solution.
* How do I define strategy?
Strategy is the tool that allows us to reach the long term goals that we could not otherwise reach.

Cool, that's the outcome.
We like outcome-based definition.
