:PROPERTIES:
:ID: e1a74f45-bb7b-46e7-8842-7977dbd48fb6
:END:
#+TITLE: twitter rpg strategy guide.txt

[[file:..][..]]

By [[id:d1e0e6bd-d0ce-4880-acc7-e4935e643ebd][visa]].
Originally posted on Twitter:
https://twitter.com/visakanv/status/1094684057173016581

I decided I wanted to take this text seriously, so I'm transcribing and editing for sane HTML formatting.
What follows is Visa's words, not mine.

Visa, if you read this and want me to take this down, please let me know.

---Teodor

* twitter rpg strategy guide.txt

Twitter is a multiplayer real-time virtual world, primarily text-based with limited multimedia support.
It combines elements of role-playing games, hack and slash, player versus player, interactive fiction and online chat.

Players can read, view and contribute descriptions of objects, other players, non-player characters, and actions performed in the virtual world, as well as the "real" world.
Players typically interact with each other by utilizing strings that resemble natural language.

While traditional MUDs typically implement RPGs set in distinct fantasy worlds populated by fictional races and monsters, with players choosing classes in order to gain specific skills or powers, Twitter allows every player to project their own fantasy and define their own game.

The flexible nature of Twitter makes it difficult for any singulra definition of "the game" to become canonical. Conflict between players with different interpretations of Twitter is a key feature of Twitter itself.
Indeed, one of the most popular games is "hey, fuck that guy".

Unsurprisingly, few players put much thought into precisely defining the game that they are playing.
Most players "pick it up" organically as they go along, inheriting the unwritten rules and norms of their peers via imitation and (limited) experimentation.

Twitter is also searchable, and allows tweets to be "threaded" in chains.

This allows skilled players to build incredibly complex tapestries of hypertext, consisting of thousands of tweets.

Why would such prolific players choose Twitter as a medium, rather than "websites" or "books", which appear to be better suited to large volumes of content?

Because Twitter allows any player to interact with any other player's tweets.

Most casual players do not appear to have caught on to the true potential utility of Twitter, or perhaps they are indifferent to it.

A web of tweets is a living entity that allows players to meet, interact and engage with 1000s of others /at the level of individual thoughts/.

Properly constructed, a web of tweets allows you to:

- witness how other players discover your tweets, via their patterns of likes, retweets and quote tweets

- connect each fragmented thought and experience into the part of a greater whole

- recognise and embellish patterns in your own play.

We have not even begun talking about relationships.
People can build relationships with other players over time and shared interactions.
Through cooperation, multiple players can share and merge webs with one another, helping each other find and share the desired information.

Players observed to be "good" and "fun" have even been known to invite each other to meetups, offer each other jobs, become "friends" outside of Twitter.
Twitter is a game with extremely real stakes and consequences, both good and bad.

You are not limited to a single identity or account on Twitter.
A single individual can play as many different players simultaneously.
You can invent entirely different identities and have radically different experiences with each.

Any player can significantly improve their experience of Twitter by examining their own usage and evaluating it against their own desires and goals.

At any moment, any player can completely change their experience of Twitter by deciding to play it differently.

- Who are you following? Why?
- What are you tweeting? Why?
- What exeriences would you like to have? Why?
- Who would you like to play with? How? Why?

With a little introspection, Twitter can be a tool for self-inquiry, making friends, testing ideas, messing around, finding information, practicing speech, and pretty much anything you like.

It's also, like everything else, just a game.

Have fun!

[16 days of silence]

Honestly, I'm still not done geeking out about how great Twitter is.
Any tweet from any thread can be reused on any other thread,,,
do you guys realise how wild that is???
It allows you to create your own cinematic universe.

#+begin_verse
follow curiosity
develop taste
publish writing
make friends
#+end_verse

#+begin_quote
twitter allows me to do ALL OF THOSE THINGS SIMULTANEOUSLY

branch 👉 https://twitter.com/visakanv/status/1094208757049905152
#+end_quote

* Teodor's commentary
** 2023-05-20
*** "strings that resemble natural language"
😂

There's so much weirdness on Twitter.
