:PROPERTIES:
:ID: 32aef0d5-4e6e-4890-bd4d-37b3dbc50e75
:END:
#+TITLE: Serial Focus

[[file:..][..]]

** No Focus

I did something I didn't like:
I had my phone in my hand browsing "social" media, and I couldn't remember deciding to check my phone.
It's a loss of control.

It's also a loss of connection to what's happening right now.
Which I noticed /again/ playing Borderlands 4 a few days ago.
I figured, since this is just running around and shooting, why not put on a podcast while playing?
So I did.
And the game lost its texture.
I was now listening to the podcast, and no longer playing the game.
Which is super ironic, a game built with speed, colors and explosions, you't think it was /the/ dopamine bomb.
Nope, a podcast sent all that straight to the background to be ignored.
The game was no longer fun!

** Focus

I cut the podcast, and got into the game again.

Sure, you can play the game just running for markers, spamming mouse1 on enemies, ignoring the story.
Or you can pay attention.
Sure, you can walk around totally disconnected from the life you're living, suffering chronic boredom awaiting escape.
Or you can live, right now.

I want to live, right now.

** Serial Focus

Serial focus means focusing on the now until you know it for what it is.
No jumping away before it's sunk.
No more immediate other things because the present is boring.
Serial focus is protection.
It protects your control: you decide, not flashes on a screen.
It protects your experience of texture: everything, in more detail.

Let the moment sink in.
Finish it properly.
/Only then/, find the next thing you'd like to focus on.
One thing at a time.

** Natural focus

When is the right time to change focus?
I don't have a recipe, but it should feel natural.

You feel done with the last thing.
You're relaxed, alert.
Your curiosity tingles.
