:PROPERTIES:
:ID: 32aef0d5-4e6e-4890-bd4d-37b3dbc50e75
:END:
#+TITLE: Serial Focus

[[file:..][..]]

I did something I didn't like: checking my phone without remembering to choose to check my phone.
It's a loss of control.

It's also a loss of connection to what's happening right now.
Which I noticed /again/ playing Borderlands 4 a few days ago.
I figured, since this is just running around and shooting, why not put on a podcast at the same time?
So I did.
And the game lost all fun.
I was now listening to the podcast, not paying attention to the game.
Which is super ironic, a game built with speed, colors and explosions, you't think it was /the/ dopamine bomb.
Nope, a podcast sent all that straight to the background to be ignored.
The game was no longer fun!

I cut the podcast, and got into the game again.

Sure, you can play the game just running for markers, spamming mouse 1 on enemies and ignoring the story.
Or you can pay attention.
Sure, you can walk around totally disconnected from the life you're living, suffering chronic boredom awaiting escape.
Or you can live, right now.

I want to live, right now.

Serial focus means focusing on the now until you know it for what it is.
No jumping away before it's sunk.
No more immediate other things because the present is boring.
Serial focus is protection.
It protects your control: you decide, not flashes on a screen.
It protects your experience of texture: everything, in more detail.

Let the moment sink in.
Finish it properly.
/Only then/, find the next thing you'd like to focus on.
One thing at a time.
