:PROPERTIES:
:ID: 37e07eec-4b5c-498a-875e-b4c4267dbfd2
:END:
#+TITLE: Don't assume trust. Build trust.

[[file:..][..]]

/Why don't they listen to me? Why don't they understand how smart I am? If I only had more power, everything would be better!!!/

I can't help but hear a whiny voice carry that statement.
The system should change!!!
It should it should it should!!!
It's not good enough!!!

In creativity, it's useful to think about the creator and the critic.
The creator creates, the critic reflects.
Together they can build amazing things.
But if one gets the upperhand, the other might get smacked into the ground.
A dominant creator will create so loudly that criticism is lost.
This is it!
It's done!
Let's make more things!
A dominant critic will point out every flaw in painstaking detail, causing all acts of creation to stop.

#+begin_quote
*M* Should we start by

*C* NO! STOP! Of course not, that's stupid!

*M* Then, perhaps

*C* Absolutely not! It's not GOOD ENOUGH!
#+end_quote

These two must work together.

Returning to our opening statement, what's wrong?

#+begin_quote
/Why don't they listen to me? Why don't they understand how smart I am? If I only had more power, everything would be better!!!/
#+end_quote

That's a dominant critic speaking.
There's no will to create, no will to take the first step.
Trust requires charity.
Someone has to take the first step.
Blaming others for not taking the first step is not helping.
Do something instead.
Start building that trust baseline that you crave.





















*References*: [[id:584e220e-be74-4079-94a9-a565624325fb][Ikke anta tillit. Bygg tillit.]], https://roamresearch.com/#/app/teod/page/QGPbEgQ_6

#+begin_quote
Jeg DIGGER å jobbe med flinke folk med selvinnsikt. Jeg digger å jobbe med nysgjerrige folk med selvinnsikt. Jeg tolererer kompetente folk uten selvinnsikt i en begrenset tidsperiode.
#+end_quote
