:PROPERTIES:
:ID: 394f1b56-753e-40d2-a51c-3fcf58bee8c1
:END:
#+TITLE: A "read it later" strategy that works

[[file:..][..]]

I've tried maintaining lists of stuff to read later again and again, but the result is always the same.
I don't read it.
At the time when I want something to read, I just do something else.
Why?

Let me speculate:

1. The friction of getting "something good" is too much. Jumping to hacker news is easier.
2. I don't just want "something random to read" --- I want to /choose/ something.
   Something that matters to me now.

I propose a solution: rich tagging & metadata for the stuff to read later + dashboards & discovery mechanisms.

Right now, I'm listening to the Metamuse podcast.
They just referred to [[https://mitpress.mit.edu/9780262140539/][A Small Matter of Programming]] --- a 1993 book by Bonnie A. Nardi.
Simply putting it in a "read it later" list is easy.
But that doesn't solve any problems.
Rather, when would I want to rediscover this?

It's easy to think topics.
Oh, this is a programming thing.

But "programming" is broad.
It's not discerning.
I'd rather want something narrow.

I propose the following relations:

| relation | value              |
|----------+--------------------|
| :from    | Adam Wiggins       |
| :from    | Metamuse (podcast) |
| :medium  | :book              |

Then filter & narrow down your [[https://fs.blog/the-antilibrary/][antilibrary]] with the relations.

Why?

Under information overload, topics alone are not enough to direct your attention.
Significance is required.
Why is this valuable?
Value judgements are made in context.
And when venturing into the unknown, you can choose to be influenced by someone who's judgement you trust.
It's a trust graph, essentially.

And you don't get stuck in a filter bubble.

:)

-----

"Soooo ... you claim that this works. But are you doing it yourself?"

Yeah. Not 100 %.
I haven't built the "read it later and tag it properly" system yet.
But the things that I've read that have really mattered have all come via references from people I trust.
This is already the way I'm reading Twitter.
I follow lots and lots and lots of people.
But I track the ones I truly pay attention to in a special list.
Then I decide whether to browse broadly (everyone) or narrowly (special list) each time I open the app.
