:PROPERTIES:
:ID: 394f1b56-753e-40d2-a51c-3fcf58bee8c1
:END:
#+TITLE: A "read it later" strategy that works

[[file:..][..]]

I've tried maintaining lists of stuff to read later again and again, but the result is always the same.
I don't read it.
At the time when I want something to read, I just do something else.
Why?

Let me speculate:

1. The friction of getting "something good" is too much. Jumping to hacker news is easier.
2. I don't just want "something random to read" --- I want to /choose/ something.
   Something that matters to me now.

I propose a solution: rich tagging & metadata for the stuff to read later + dashboards & discovery mechanisms.

Right now, I'm listening to the Metamuse podcast.
They just referred to [[https://mitpress.mit.edu/9780262140539/][A Small Matter of Programming]] --- a 1993 book by Bonnie A. Nardi.
Simply putting it in a "read it later" list is easy.
But that doesn't solve any problems.
Rather, when would I want to rediscover this?

It's easy to think topics.
Oh, this is a programming thing.

But "programming" is broad.
It's not discerning.
I'd rather want something narrow.

I propose the following relations:

| relation | value              |
|----------+--------------------|
| :from    | Adam Wiggins       |
| :from    | Metamuse (podcast) |
| :medium  | :book              |

Then filter & narrow down your [[https://fs.blog/the-antilibrary/][antilibrary]] with the relations.

Why?

Under information overload, topics alone are not enough to direct your attention.
Significance is required.
Why is this valuable?
Value judgements are made in context.
And when venturing into the unknown, you can choose to be influenced by someone who's judgement you trust.
It's a trust graph, essentially.

And you don't get stuck in a filter bubble.

:)

-----

* Appendix A: do you have skin in the game?
Yeah. No. Not exactly.
I haven't built the "read it later and tag it properly" system yet.
But the things that I've read that have really mattered have all come via references from people I trust.
This is already the way I'm reading Twitter.
I follow lots and lots and lots of people.
But I track the ones I truly pay attention to in a special list.
Then I decide whether to browse broadly (everyone) or narrowly (special list) each time I open the app.
* Appendix B: how do you propose we implement this, exactly?
Good point.
I don't want to manage new pages with {folder,play.edn,index.html} and stuff for each new entity.
But perhaps a recommendation can have an UUID.
And entities can list up their recommendations?

🤔

I think that could work.
Then I just need an entity for Adam Wiggins and/or [[id:e33962d6-d5cb-4ef8-b7be-9d4a537edbec][Metamuse (podcast)]].
And the "box of unpaged entities" can be a folder of EDN files.
That's built into the index.

🤔

* Appendix C: attention design for reading it later

Given:

1. list of people with ideas
   1. each person has refernces
2. my needs / values & interests

I want:

1. To discover & learn new interesting stuff

xx

So. How do I apply [[id:0cc48734-e933-44cb-a4e8-2678f125f6df][Attention design]] to this?

#+BEGIN_VERSE














#+END_VERSE
