:PROPERTIES:
:ID: 394f1b56-753e-40d2-a51c-3fcf58bee8c1
:END:
#+TITLE: Reading it later

[[file:..][..]]

I've tried maintaining lists of stuff to read later again and again, but the result is always the same.
I don't read it.
At the time when I want something to read, I just do something else.
Why?

Let me speculate:

1. The friction of getting "something good" is too much. Jumping to hacker news is easier.
2. I don't just want "something random to read" --- I want to /choose/ something.
   Something that matters to me now.

I propose a solution: rich tagging & metadata for the stuff to read later + dashboards & discovery mechanisms.

Right now, I'm listening to the Metamuse podcast.
They just referred to [[https://mitpress.mit.edu/9780262140539/][A Small Matter of Programming]] --- a 1993 book by Bonnie A. Nardi.
Simply putting it in a "read it later" list is easy.
But that doesn't solve any problems.
Rather, when would I want to rediscover this?

It's easy to think topics.
Oh, this is a programming thing.

But "programming" is broad.
It's not discerning.
I'd rather want something narrow.

I propose the following relations:

| relation | value              |
|----------+--------------------|
| :from    | Adam Wiggins       |
| :from    | Metamuse (podcast) |
| :medium  | :book              |

Then filter & narrow down the /unlibrary/ with the relations.

Why?

Under information overload, topics alone are not enough.
Significance is required.
Why is this valuable?
Value judgements are made in context.
And when venturing into the unknown, you can choose to be influenced by someone who's judgement you trust.
It's a trust graph, essentially.

And you don't get stuck in a filter bubble.

:)
