:PROPERTIES:
:ID: 86c31b09-2831-4435-a73e-91db76fcbd57
:END:
#+TITLE: Bink: Bookmarks as data

[[file:..][..]]

#+BEGIN_VERSE
<rant>
THIS PROGRAM MAY NOT WORK
THIS PROGRAM WILL CHANGE
IF THIS PROGRAM CRASHES, YOU MAY NOT RECEIVE SUPPORT
USE THIS PROGRAM AT YOUR OWN RISK
</rant>
#+END_VERSE

* Bookmarks should live in Git!
I gave up on managing bookmarks in web browsers long ago.

But I was thinking.
We're able to take care of source code.
Improve it over time.
And we've got this /amazing/ thing called /version control/.
And this other amazing thing called /data/.
So why not combine them.

Bookmarks are just data.

But!
Opening a bookmark must be nice.
Run a command, select the bookmark, open in browser.

So I made a thing.
Use it like this:

1. Run =$ bink= in a terminal
2. Select a bookmark
3. It opens in Firefox

But the bookmarks are just a bunch of EDN files you can structure yourself in =~/.config/bink/provider/=.
Here's an example:

#+begin_src clojure
;; from ~/.config/bink/provider/links.edn on my computer:
{:links [{:title "Clojure Deref" :href "https://clojure.org/news/news"}
         {:title "Clojureverse" :href "https://clojureverse.org/"}]}
#+end_src

If you want to try it out, that's awesome.

Feel free to bug me about it on the babashka channel on the Clojurians Slack.

Here's a small install script: https://github.com/teodorlu/play.teod.eu/blob/master/bink/install.sh
* Dev journal / working notes
Feel free to ignore this part :)

Or not.
You decide.
** 2022-09-14
*** CLI draft
#+begin_src
# To open a link:
$ bink
# Select link with fzf
# Then it's opened in your browser.

# Add a link
$ bink add "Clojure Deref" https://clojure.org/news/news
#+end_src
*** Nice to have: link providers
Nice to have / later: link providers.
I could fetch links from multiple sources.
Use one source with my team at work.
Another for personal stuff.

A link provider could be an EDN file, a JSON file, an SQLite DB, an URL or a system command.

But! Let's not start there.
Or ...
It would be nice to be able to just symlink multiple files / programs into ~/.local/share/bink/providers.d/

Hmmm.
*** Config
| Path                        | Purpose                      |
|-----------------------------+------------------------------|
| =~/.config/bink/config.edn= | Bink main configuration file |
| =~/.config/bink/provider/*= | Additional link providers    |
*** Link providers
JSON file - interpret as JSON.
EDN file - interpret as EDN.

What about programs?
If they are executable, perhaps they should be run?

Perhaps an executable =links.json= should output JSON links on stdout.
🤔
*** Link file format
EDN:

#+begin_src clojure
{:links [{:title "Clojure Deref" :href "https://clojure.org/news/news"}
         {:title "Clojureverse" :href "https://clojureverse.org/"}]}
#+end_src

JSON:

#+begin_src json
{
    "links": [
        {"title": "Clojure Deref", "href": "https://clojure.org/news/news"},
        {"title": "Clojureverse", "href": "https://clojureverse.org/"}
    ]
}
#+end_src
