:PROPERTIES:
:ID:       cd48d901-8e1b-4d10-9b5a-76002e426dc0
:END:
#+title: Prefer narrow statements

[[./..][..]]

Idea: Coordination is easier when statements are narrow

Narrow /interpretation/ of statements requires:

- Statement is composed of narrow pieces
- Context where statement is interpreted is aware of the pieces

* Challenge: narrow statements require more precise language than vague statements.
Changing the way we speak is hard.
Unfamiliar.
Moving to precise language from context-laden language is hard!
Why should others join me?

* Should new language pieces be introduced?

  I say yes

  Otherwise there is no improvement

  sharing new language requires communication - interplay - idea movement - idea enrichment

* How should a group share knowledge?

** Requirement - narrow statements

** Strategy for achieving narrow statements

Pre-shared agenda of topics - "is this something you care about?"

Each topic is introduced by someone

Then there are questions / criticisms.

* Retrospective
** 2022-07-24
This makes no sense:
#+begin_quote
- Context where statement is interpreted is aware of the pieces
#+end_quote

Wait, I remember what I meant.
Narrow statements use words.
The meaning of the words must be meaningful for the receiver to understand the meaning.
