:PROPERTIES:
:ID: 55261ada-7ca6-4c94-88f5-446a9b35e5c4
:END:
#+title: Interaction value differential

[[./..][..]]

Ever asked a world-leading expert for help?
Did you feel shy?
Why do you think that is?

Two parties rarely get the same amount of value out of an interaction.
When we know each other well, we share context.
That reduces friction, and makes it easier to get something valuable out.

When I interact with someone I don't know, I tread lightly.
I don't know what our shared ground is.
I don't know what we both value.
Will I contribute to what this person needs, or am I distracting?

That feeling of "how much of her time can I spend?" is how your phsyche manifests the difference in percieved value for you and the expert in the interaction.
You don't want to waste their time.

Does that mean you should not ask for help?
I say no.
But it does shape /how/ you should ask for help.

I choose to assume that people are fundamentally good.
People do want to help you.
They just have an infinite number of other things they could do too.
Experts in particular.
They can choose to help you.
Or help someone else, advance their field, or spend time with frends and family.

Therefore, respect their time.
Don't chat to make the time pass.
Make it exceptionally easy to help you.
Where are you stuck?
How can they help you?
How can you minimize the amount of time required to get you unstuck?

Do that.
Make sure they can reply to you on their own schedule, when they have time.
Don't assume this is the regular easy-going conversation you prefer with your friends.
If the relationship turns casual, sure, welcome that.
But don't require that.
Make casual interaction an option /they/ can choose to take.

By making it exceptionally easy to help you, you maximize your chance to get an initial reply.
Then demonstrate that you've taken their advice to heart before you ask again.
Next time you need help, first share how you benefited last time.
You're grateful, after all!
Show them that the time invested in you was well spent.
Then ask for something else that they can easily give you.

Repeat, and you might gain a mentor.
