:PROPERTIES:
:ID: 55261ada-7ca6-4c94-88f5-446a9b35e5c4
:END:
#+title: How to ask experts for help

[[./..][..]]

Have you ever asked a world-leading expert for help?
Did you feel shy?
Why do you think that is?

Two parties rarely get the same amount of value out of an interaction.
When I'm chatting with a fiends, we share lots of context.
We know each other.
We care about each other.
And we can get to the point quickly.
Shared context reduces friction, and makes the conversation more valuable for both parties.

When I interact with someone I don't know, I tread lightly.
I don't know what our shared ground is.
I don't know what we both value.
Will I contribute to what this person needs, or am I yet another source of stress in a busy day?

That feeling of "how much of her time can I spend?" is your psyche telling you that you are getting more out of the interaction than the expert.
You don't want to waste their time.

Does that mean you should not ask for help?
I say no.
But it does shape /how/ you should ask for help.

I choose to believe that people are fundamentally good.
People do want to help you.
They just have an infinite number of other things they could do too.
Experts in particular.
They can choose to help you.
Or help someone else, advance their field, or spend time with friends and family.

Therefore, respect their time.
Don't chat to make the time pass.
Make it exceptionally easy to help you.
Where are you stuck?
How can they help you?
How can you minimize the amount of time required to get you unstuck?

Do that.
Make sure they can reply to you on their own schedule, when they have time.
Don't assume this is the regular easy-going conversation you prefer with your friends.
If the relationship turns casual, sure, welcome that.
But don't require that.
Make casual interaction an option /they/ can choose to take.

By making it exceptionally easy to help you, you maximize your chance to get an initial reply.
Did their advice work?
Were you able to solve your problem?
Let them know!
This is likely not the first time they've helped someone.
By sharing how you benefited from their feedback /you are helping them/ become better mentors.
Show them that the time invested in you was well spent.
Then ask for something else that they can give you easily.

Repeat, and you might gain a mentor.
