:PROPERTIES:
:ID: 9f52d562-4a06-4ea1-a461-2018fca5baf1
:END:
#+TITLE: there's always a deliverable

[[file:..][..]]

DRAFT

This article lacks polish, cohesion and effort.
If you're interested, please let me know.

Consider reading this other piece that touches on the same content:
[[id:842f9b9a-de98-4187-863e-3e6cf1b1814d][What's a good intersection between work and play?]]

-----

In tactical work, there's a deliverable.
In strategic work, there's a deliverable.

Just because realized end user value is further away, that doesn't mean we can't deliver something specific.
We just have to define our impact in terms of an intermediate goal, not the end state.

Strong values make intermediate goals easier.
With strong values, simply staying true to your values is a goal in itself.

First, the default---write journal. Something like [[id:bd776ab0-d687-4f16-b66d-d03c86de2a2e][My public journal]].

/what do I want to put in this article?/

Idea: apply [[id:c8131839-be8d-4ca8-8bc3-eac72cfade15][Capability, feature and assembly]] to knowledge work.
A capability is a mental model, a definition.
A utility (feature) provides value in a context.
As a text, it motivates /why/. (see [[id:93ea907e-9dcb-4c6b-af7d-d9bc22c34d57][Aphorisms]], number 5).
An assembly solves for /discovery/.
How can I know what's available?
Where do I start?
