[package]
name = "demo-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.6"
ctrlc = "3.2.2"
nix = "0.24.1"
tokio = { version = "1.18.2", features = ["full"] }

[features]
