:PROPERTIES:
:ID: 9c67d806-b806-4c24-8c98-2e19443b9794
:END:
#+TITLE: Support, challenge, carry

[[file:..][..]]

DRAFT

Support: How can I make others good, powerful?

Challenge: What information do I need to feed back into the system in order for it to run smoother?

Carry: Is it time for me to lead?

*frame: carry and support in league of legends*
Provide some examples, video.

*frame: carry and support in Age of Empires*.
More examlpes!

*stepwise: support ➡ challenge ➡ carry*
Why?
Because playing support is easier -- you don't need to /define/ the rules of the game to play nice.
But why is that?
Because theory does not need to precede practice!
If you want to paint, paint.
If you want to write, write.
If you want to build, build.
To define the rules of the game is to design theory.
And designing good theory is /way/ easier when you can keep some application of that theory in mind.

*dynamic initiative*.
Who should carry?
That depends on who knows the territory better -- what we're doing now, and where we're going.
As a team forms, its [[id:587fd857-1f93-4b59-935a-7681e5129665][turst, shared sense of quality, and shared intent]] will improve.
That lowers switching costs.
Questions & framings that needs to be explicit early on takes hold in a shared understanding.
With lower switching cost, it makes sense to move the initiative around.
When the switching cost reaches zero, we want the player with the best map to lead.
But can we reach "perfection"?
No.
I don't believe that's possible.
There will /always/ be information asymmetry.
The reason is plain: information asymmetry gives teams leverage.
Different people want different things.

Not: /perfect dynamic initiative/.
But: /shared understaning, charity and team willingness to support, challenge and carry/.

-----

*product lead, tech lead interaction*
I like to program, and I like to create tools that actually work well in the real world.
Why?
Programming, I just /like/.
It's a skill I like to exercise.
It's something I like to /do/.
It does come with benefits.

*create optionality*.
Dynamic initiative is good because it opens doors that are otherwise closed.
When one person leads and the rest follows, the followers are limited in how they can help improve the system in a positive direction.
When one person leads, the only options are the options that the leader /sees/.
And when the leader acts, the leader cannot do /something else/.
The leader is busy.

*dynamic initiative optimized for learning speed*.
One frame is that the best leader should lead.
Another frame is that the one best suited to learn from leading should lead.
I suggest balancing the two.
But if you are the de-facto leader, consider whether you should create space rather than push ahead right now.
It might unveil things you didn't think of.
It will enable you to put your attention elsewhere.
And the team member picking up the initiative might gain more than you could ever imagine.
Skills, obviously.
But more importantly, ownership.
You /want/ the team to take initiative towards your shared goal.
That will not happen in teams where direction is monopolized.

*start with support -- but ask WHY.*.
When starting out, play support.
Ask how you can help, then try to help.
Why?
Because that's the most solid epistemic strategy.
If you start out challenging, you'll be arguing to change something you don't know what is.
If you start out carrying, you will be setting the rules for playing the game without knowing what the goal of the game is.
But /ask WHY/.
Don't /just/ follow along.
You want to know why doing the thing you're doing makes sense.
You want to /gradually/ move towards knowing with [[id:028a2171-3146-4fbc-8d5d-3209675dae8b][value in context]] you're providing.
You want to [[id:b21e4aea-7282-45e8-83a3-2d80ecdf669b][learn to discover]].
But you don't need to put a ton of effort into that in the beginning.
You asked how you could help.
What was the answer you got?
Did that answer make sense?
After a week or two, does the initial answer still make sense?
Is it a part of some larger whole, or just some gibberish someone made up?
Consider challenging a bit!

*challenge around your expertise*.
As you get more comfortable, challenge.
And don't challenge in a supid, denegrating way.
Don't assume people are idiots, follow the [[id:7e870f15-eed2-4974-8cb8-121620f87288][Principle of Charity]].

*then pick an option, and carry it*.
An option is something you can capitalize on.
A potential for value sometime in the future.
Why not help explore that option!
Light your torch, and venture into the unknown.
