:PROPERTIES:
:ID: 3eab9578-dec5-4c21-b5b6-7c18d6258d62
:END:
#+TITLE: The Commons

[[file:..][..]]

DRAFT

The commons is the place we share.
It is the place that is not within the domination of an individual.
It is the place governed not by the will of one, but by the collective.
No one dominates the other.

Who enters the commons?
Research into common spaces (refer to that Nobel Prize economics essay from the 70s) suggests that there must be rules for who can enter the commons.
Otherwise, the commons may end in tragedy.

Commons give us meaning.
It is in shared spaces that we understand who we are.
It is in shared spaces we can see who we are.

* 2023-05-29
** References
Elinor Ostrum

#+begin_quote
Elinor Claire "Lin" Ostrom (née Awan; August 7, 1933 – June 12, 2012) was an American political scientist and political economist[1][2][3] whose work was associated with New Institutional Economics and the resurgence of political economy.[4] In 2009, she was awarded the Nobel Memorial Prize in Economic Sciences for her "analysis of economic governance, especially the commons", which she shared with Oliver E. Williamson. She was the first woman to win the Nobel Prize in Economics.[5]

Source:
https://en.wikipedia.org/wiki/Elinor_Ostrom
#+end_quote

Governing the Commons
The Evolution of Institutions for Collective Action
https://www.cambridge.org/no/academic/subjects/politics-international-relations/political-theory/governing-commons-evolution-institutions-collective-action-1?format=PB&isbn=9781107569782
(I haven't read this)
