:PROPERTIES:
:ID: afce0ad0-0723-4b19-a7bf-1e9da412045f
:END:
#+TITLE: Trust vs Evil

[[file:..][..]]

Evil organizations as depicted in fantasy often lack trust.

Evil differs from good in /defection/: an evil party does not hesitate to lie, deceive and exploit.
The good are honourable, speak the truth, and aim to help.

It is easy to think that evil will prevail /because it knows no bounds/.
How can someone limited by stricter morals prevail against someone with no rules?

Pay attention to what happens when evil interacts with evil.

Because evil deceives, evil will deceive evil.
Each member of the evil organization will necessarily have to watch their back to ensure that they themselves are not being deceived right now.
In order to make anything happen, it is necessary to apply force, threats and punishment.
All that forcing, threatening and punishing requires coordination.

In good organizations, coordination is simpler.
Lies, deception and exploitation is punished.
If you abuse the trust of an ally, you will not only destroy your relationship with that person.
You will destroy your own reputation within the organization, and you will struggle to get help.

Reputation for honor travels before you.
Your past actions influence how new people meet you for the first time.
You will be able to build that reputation.

Ultimately, values spread.
You will choose to interact with people you can trust.
Then you will learn to those people to judge other people: those who you trust themselves trust others.
You can to some extent trust those people.
