#+title: Discover the difference
:PROPERTIES:
:ID: 57b71ae8-5038-40cd-b239-9e82c3bf9d74
:END:

[[./..][..]]

DRAFT - UNFINISHED

Alternative titles: /Discover diversity/, /Discover options/, /Option discovery/, /Expand and contract in design thinking/

# WHY CAN'T WE AGREE ON ANYTHING?

* Notes 1

There's friction between the need to discover options and stick to one path.
Friction between improving optionality and keeping cohesion.
Are we doing the right thing now?
Should we be doing something else?

If we want to keep our options open, how large is an option?
A day?
A week?
A three month effort by four people?

When should we improve optionality versus clean up all the paths not taken?

Tension: "we want to experiment" vs "we're fragmented -- our effort is all over the place".

I think this is just me rediscovering design thinking.
Widen phase: get options down on the table.
Narrow phase: bring value to completion.

Individual developer: how much execution vs workflow experimentation?
Individual product manager: "wide net product discovery" vs "does this thing work".
Two weeks of team effort: what value are we providing now? What's the time frame? Value for whom?

* Notes 2

This title is bad.
Vague.
"discover the difference" does NOT convey the intent right.

But what should the title be?
Stochastic thinking?
Don't narrow too fast?
Expand / contract in design thinking?

* Where is the pain?

The pain is when we narrow too fast.
When we seek to add structure too early.
When the narrow, clear interpretation wins over the uncertain one --- just because it's clearer.

Is there a way out?

1. Talking clearly about objectives / problems helps.
   If problems and solutions are considered separately, we're able to discuss the what cleanly before honing in on the why.
2. Ensure that just because there's a developer in the room, the developer is not responsible for having to build the whole thing discussed in a day.

* More titles

1. What first - then why
2. Why discuss the what?
3. What's better - before how better?

* More titles

1. discussions-expand-contract --- Discussions - expand or contract?
   - Expanding and contracting in discussions

* I learned to appreciate difference only after learning product discovery

🤔
