:PROPERTIES:
:ID: 5679f20c-6564-4020-816d-0575c6456451
:END:
#+TITLE: Teodor's school system

[[file:..][..]]

DRAFT

What+how should we teach kids?

That's a problem I'd love the chance to work on at some point in my life.

This document is highly subjective, and is likely to change.
The problem is hard, and has been worked on by smart people.

* 2023-05-27
** Subjects
My best bet per 2023-05-27 is these four (in alphabetical order):

- Aesthetics.
- Analysis
- Literature
- Movement

Then encourage activities that combine the subjects, for example dance (movement and aesthetics) or system design (aesthetics and analysis).

- *Aesthetics*. Visuals, taste, food. History of art.
- *Analysis*. Science, reason, logic, mathematics, physics, machines.
- *Literature*. Writing, reading, communicating, speaking. Theater.
- *Movement*. Dance, swimming, running, BJJ.

Problem: where is the adventure?
Where is the movement into the unknown?
Perhaps that's not a problem, perhaps that's just a combination.
/Movement/ into the unknown, in order to find something /aeshetically/ better.
/Analysis/ of whether it's better, /literature/ about the journey.

Goal: living in a moldable system.
This sort of combines all the things.
Don't give kids ipads.
Give kids something they can explore the inner workings of.
And something that encourages that exploration /together/.
(ie what Kay, Papert, et al seem to conclude)

Goal: encourage people that they can /change their circumstances for the better/.
Your environment is not static, it's dynamic.
Your environment is meant to be lived in.

Goal: find joy in all four.
Joy in aesthetics: "This feels /right/ to me".
Joy in analysis: "Playing around with this machine is /fun/, it lets me see better, understand better".
Joy in literature: "Man this story is engaging! I want to take part!"
Joy in movement: "I feel the flow!"
** otfrom comments: Where is "Expression"?
From [[id:8638f5d6-bc22-4f10-a457-ab388c22128b][the Clojurians Slack]] ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685180318899499][thread link]]):

#+begin_quote
I think you are missing "Expression" in your 4 overarching things. It might be captured in your activities for the other four, but it would be easy for it to be formulaic without having the ability to express what you want as one of the goals/subjects.

Expression is why I do free writing 5 days per week and I find it difficult to keep going, but rewarding when I do because the practice makes it easier for me.

Though all of us here do a lot of expressing as building something in code is a form of expression (regardless of what that thing is)

---otfrom
#+end_quote

My reply:

#+begin_quote
hmmm.

Is "expression" a way to "make it real"? Like practicing a real instrument in order to play a song "for real" for someone at some point in time?

I think you have a point.

When I look back at when I went to school, it seemed fake. Fake history: read some years to present on a test. Fake English: read some words to remember them for a test.

---teodorlu
#+end_quote
* 2023-05-29
** My summary of more comments from the Clojureverse thread
Note: these are not my ideas, only my summary of the ideas.
If you want the source, please read [[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685180318899499][the thread]].

1. [[id:a172782b-bceb-4b44-afdf-7a2348d02970][Rich Hickey]] has touched on "expression" in [[id:73b93aeb-d61a-413d-a119-53335e73afda][Design, Composition and Performance]] and "performance"
2. How should this schools system be funded?
   - Norwegian public schools have large classes (20 to 30 kids) and tightly, centrally controlled curriculums.
   - Private schools cost a lot and amplify socio-economic differences.
   - In bad schools, there are often no good teachers to set good examples.
3. Expression is a way to use what you've learned to get a chance to move beoyond it.
   Also, learning to express yourself in some way is important. ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685222191964799?thread_ts=1685180318.899499&cid=CBJ5CGE0G][source]])
   1. Free writing every day is a way to exercise expression ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685266145263599?thread_ts=1685180318.899499&cid=CBJ5CGE0G][source]])
   2. Prompts can be used to break free of writing the same thing every day ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685266213307359?thread_ts=1685180318.899499&cid=CBJ5CGE0G][source]])
4. Creative expression typically requires constraints in order to avoid the "tyranny of the blank canvas"
5. There's tension between "education for workers" and "education for thinkers" ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685266708417809?thread_ts=1685180318.899499&cid=CBJ5CGE0G][source]])
6. Education
   1. Teodor's current understanding:
      1. Western education is based on /skills/ (techne), eastern education is based on principles
      2. Don't feel like I have a grasp on eastern thinking.
         The western approach sometimes feels "dead".
      3. Not sure how I should approach learning this.
         Perhaps living in it is required, that even the question "is there a book I can read?" builds in the (western) assumption that this can be learned from books.
         The Beatles went to India.
         This cool Norwegian singer/songwriter I got the chance to talk to went to India to train his vocals, and enjoyed the experience.
7. "The categories overlap in many interesting ways that are not clear in their presentation here. Maybe a Venn-ish diagram would be better? (Trivial example: dance is movement + aesthetics.)" ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685357099012009?thread_ts=1685180318.899499&cid=CBJ5CGE0G][source]])
8. "A missing category here is emotional education. One of the most important things we learn in the course of life is to cease to be a slave to emotional impulses, while also remaining in touch with the important things they tell us." ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685357099012009?thread_ts=1685180318.899499&cid=CBJ5CGE0G][source]])
