:PROPERTIES:
:ID: 5679f20c-6564-4020-816d-0575c6456451
:END:
#+TITLE: Teodor's school system

[[file:..][..]]

DRAFT

What+how should we teach kids?

That's a problem I'd love the chance to work on at some point in my life.

This document is highly subjective, and is likely to change.
The problem is hard, and has been worked on by smart people.

* 2023-05-27
** Subjects
My best bet per 2023-05-27 is these four (in alphabetical order):

- Aesthetics.
- Analysis
- Literature
- Movement

Then encourage activities that combine the subjects, for example dance (movement and aesthetics) or system design (aesthetics and analysis).

- *Aesthetics*. Visuals, taste, food. History of art.
- *Analysis*. Science, reason, logic, mathematics, physics, machines.
- *Literature*. Writing, reading, communicating, speaking. Theater.
- *Movement*. Dance, swimming, running, BJJ.

Problem: where is the adventure?
Where is the movement into the unknown?
Perhaps that's not a problem, perhaps that's just a combination.
/Movement/ into the unknown, in order to find something /aeshetically/ better.
/Analysis/ of whether it's better, /literature/ about the journey.

Goal: living in a moldable system.
This sort of combines all the things.
Don't give kids ipads.
Give kids something they can explore the inner workings of.
And something that encourages that exploration /together/.
(ie what Kay, Papert, et al seem to conclude)

Goal: encourage people that they can /change their circumstances for the better/.
Your environment is not static, it's dynamic.
Your environment is meant to be lived in.
