:PROPERTIES:
:ID: 5679f20c-6564-4020-816d-0575c6456451
:END:
#+TITLE: Teodor's school system

[[file:..][..]]

DRAFT

What+how should we teach kids?

That's a problem I'd love the chance to work on at some point in my life.

This document is highly subjective, and is likely to change.
The problem is hard, and has been worked on by smart people.

* 2023-05-27
** Subjects
My best bet per 2023-05-27 is these four (in alphabetical order):

- Aesthetics.
- Analysis
- Literature
- Movement

Then encourage activities that combine the subjects, for example dance (movement and aesthetics) or system design (aesthetics and analysis).

- *Aesthetics*. Visuals, taste, food. History of art.
- *Analysis*. Science, reason, logic, mathematics, physics, machines.
- *Literature*. Writing, reading, communicating, speaking. Theater.
- *Movement*. Dance, swimming, running, BJJ.

Problem: where is the adventure?
Where is the movement into the unknown?
Perhaps that's not a problem, perhaps that's just a combination.
/Movement/ into the unknown, in order to find something /aeshetically/ better.
/Analysis/ of whether it's better, /literature/ about the journey.

Goal: living in a moldable system.
This sort of combines all the things.
Don't give kids ipads.
Give kids something they can explore the inner workings of.
And something that encourages that exploration /together/.
(ie what Kay, Papert, et al seem to conclude)

Goal: encourage people that they can /change their circumstances for the better/.
Your environment is not static, it's dynamic.
Your environment is meant to be lived in.

Goal: find joy in all four.
Joy in aesthetics: "This feels /right/ to me".
Joy in analysis: "Playing around with this machine is /fun/, it lets me see better, understand better".
Joy in literature: "Man this story is engaging! I want to take part!"
Joy in movement: "I feel the flow!"
** otfrom comments: Where is "Expression"?
From [[id:8638f5d6-bc22-4f10-a457-ab388c22128b][the Clojurians Slack]] ([[https://clojurians.slack.com/archives/CBJ5CGE0G/p1685180318899499][thread link]]):

#+begin_quote
I think you are missing "Expression" in your 4 overarching things. It might be captured in your activities for the other four, but it would be easy for it to be formulaic without having the ability to express what you want as one of the goals/subjects.

Expression is why I do free writing 5 days per week and I find it difficult to keep going, but rewarding when I do because the practice makes it easier for me.

Though all of us here do a lot of expressing as building something in code is a form of expression (regardless of what that thing is)

---otfrom
#+end_quote

My reply:

#+begin_quote
hmmm.

Is "expression" a way to "make it real"? Like practicing a real instrument in order to play a song "for real" for someone at some point in time?

I think you have a point.

When I look back at when I went to school, it seemed so fake. Fake history: read some years to present on a test. Fake English: read some words to remember them for a test.

---teodorlu
#+end_quote
