:PROPERTIES:
:ID: 9349d376-d5ee-458b-884c-b35cce2aa296
:END:
#+TITLE: The Origins of Opera and the Future of Programming

[[file:..][..]]

#+begin_export html
<iframe class="youtube-video" src="https://www.youtube.com/embed/pEQj7fy-Htg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export

By [[id:cf8109c8-bed4-4b1c-bcff-a84e576d4043][Jessica Kerr]].

#+begin_quote
There’s a story to tell, about musicians, artists, philosophers, scientists, and then programmers.
There’s a truth inside it that leads to a new view of work, that sees beauty in the painful complexity that is software development.
Starting from The Journal of the History of Ideas, Jessica traces the concept of an “invisible college” through music and art and science to programming. She finds the dark truth behind the 10x developer, a real definition of “Senior Developer” and a new name for our work and our teams.

Jessica Kerr is a developer of development systems. She works remotely from St. Louis, for Atomist, where she writes automations and automation infrastructure in TypeScript, Clojure, and whatever else is needed. She is a back-end developer who believes the front-end is most crucial. Jessica speaks at conferences in the US and Europe; find her on the Code podcast (greaterthancode.com)
#+end_quote

Also known as /Collective Problem Solving in Music, Science, Art, and Software/ ([[https://jessitron.com/2019/11/05/keynote-collective-problem-solving-in-music-science-art-and-software/][source]]).
