:PROPERTIES:
:ID: dde82bbc-e4c8-49c0-b577-dba0cba0bdf7
:END:
#+TITLE: The Beginning of Infinity

[[file:..][..]]

https://en.wikipedia.org/wiki/The_Beginning_of_Infinity

Book by [[id:369abfa2-8b8c-4540-958f-d0fce79f132b][David Deutsch]].
Excerpt from the introduction:

#+begin_quote
In this book I argue that all progress, both theoretical and practical, has resulted from a single human activity: the quest for what I call good explanations.
#+end_quote

My definition of design, influenced by David Deutsch, Rich Hickey and Zach Tellman:

Design is the art of tastefully narrowing the distance between elegant, ergonomic, general tools and effective application in specific context. (left is unnamed, right is [[id:31478ab4-b7bf-4c87-8dae-8adb66690571][Utility is Contextual]]) (see also [[id:dde82bbc-e4c8-49c0-b577-dba0cba0bdf7][The Beginning of Infinity]], which heavily influenced this statement)
(I think left might be aesthetics & beauty. or elegance.)

* Meanings of "The Beginning of Infinity" encountered in /The Beginning of Infinity/
I am absolutely thrilled by multiple aspects of this book.
Its clarity, its taste.
Its pedagogy.

The book /The Beginning of Infinity/ centers around the term "The Beginning of Infinity".
Each chapter digs deeper, providing more more context, more connections.

But the chapters can be long and complicated.
I'm often left encouraged but confused, not sure exactly what I've just learned.

Deutsch anticipates this.
Chapters begin with a big text, and end with a small conclusion.
The main part reads like normal prose.
It motivates an idea, defines that idea, and explores its implications.
The conclusion is /small/.
It takes a vague "cloud" of an idea and sharpens it.
Makes that idea /crisp/.
In that conclusion there is always a list:
/Meanings of "The Beginning of Infinity" encountered in this chapter./

I loved reading those lists.
So much I want to give them more attention than merely reading them.
So I list them here :)

Each chapter also contains a list of terms and definitions.
I'll include some of those too.

*Chapter 1: The Reach of Explanations*

"The Beginning of Infinity" is:

- The fact that some explanations have reach.
- The universal reach of some explanations.
- The Enlightenment.
- A tradition of criticism.
- Conjecture: the origin of all knowledge.
- The discovery of how to make progress: science, the scientific revolution, seeking good explanations, the political principles of the west.
- Fallibilism.

*Chapter 3: The Spark*.

Terminology:

- Person :: An entity that can create explanatory knowledge

"The Beginning of Infinity" is:

- The fact that everything that is not forbidden by nature is achievable, given the right knowledge.
  "Problems are soluble."
- The "perspiration" phase can always be automated.
- The knowledge-friendlyness of the physical world.
- People are universal constructors.
- The beginning of the open-ended creation of explanations.
- The environments that could create an open-ended stream of knowledge, if suitably primed --- i.e. almost all environments.
- The fact that new explanations create new problems.
* Appendix A: this article lacks specificity.
Listing up /just synthesis/ without giving motivating examples is not providing [[id:028a2171-3146-4fbc-8d5d-3209675dae8b][value in context]].
This article would be better --- more useful --- if I could /anchor/ it.
But that's okay.
It's okay for me to have incomplete stuff on here.
It's for play, after all :)

Note from 2022-10-22 --- I'm kind of skeptical to this criticism.
This page /is/ missing a proper introduction.
An answer to why this is significant to me.
See [[id:93ea907e-9dcb-4c6b-af7d-d9bc22c34d57][Aphorisms]],

#+begin_quote
5 - Never link to content without enriching the intent of linking with context.
Instead, answer "Why do I find this worthwhile?".
#+end_quote

🤔

So perhaps this article /does not/ lack specificity, but context, or meaning.
It's quite specific as it is.
It's a book summary with some commentary.

#+BEGIN_VERSE















#+END_VERSE
