:PROPERTIES:
:ID: 139bfaef-5305-4f5d-89a0-f34a61bca27d
:END:
#+TITLE: not good enough, there's no fire

[[file:..][..]]

DRAFT

T-shirt front:

#+begin_src
 
                           NOT GOOD ENOUGH
                               NO FIRE
#+end_src

on the front and

#+begin_src
 
        Prometheus stole fire from the gods and gave it to us,
                           for ... THIS?
#+end_src

on the back.

#+begin_quote
Where now are the horse and the rider? Where is the horn that was blowing?
Where is the helm and the hauberk, and the bright hair flowing?
Where is the harp on the harpstring, and the red fire glowing?
Where is the spring and the harvest and the tall corn growing?
They have passed like rain on the mountain, like a wind in the meadow;
The days have gone down in the West behind the hills into shadow.
Who shall gather the smoke of the deadwood burning,
Or behold the flowing years from the Sea returning?

   ---J.R.R Tolkien, /The Two Towers/.
      Theoden speaking to Gamling before the Uruk-hai attack Helm's Deep.
#+end_quote

Where now are the horse and the rider?
Where is the horn that was blowing?
Is it all lost?

#+begin_quote
At that sound, the bent shape of the king sprang suddenly erect.
Tall and proud he seemed again; and rising in his stirrups he cried in a loud voice, more clear than any there had ever heard a mortal man achieve before:

#+begin_verse
             Arise, arise, Riders of Théoden!
             Fell deeds awake: fire and slaughter!
             spear shall be shaken, shield shall be splintered,
             a sword-day, a red day, ere the sun rises!
             Ride now, ride now! Ride to Gondor!
 
#+end_verse

With that he seized a great horn from Guthláf his banner-bearer, and he blew such a blast upon it that it burst asunder.
And straightway all the hors in the host were lifted up in music, and the blowing of the horns of Rohan in that hour was like a storm upon the plain and a thunder in the mountains.

#+begin_verse
             Ride now, ride now! Ride to Gondor!
 
#+end_verse

Suddenly the king cried to Snowmane, and the horse sprang away.
Behind him his banner blew in the wind, thie horse upon a field of green, but he outpaced it.
After him thundered the knights of the house, but he was ever before them.
Éomer rode there, the white horsetail on his helm floating in his speed, and the front of the first /éored/ roared like a breaker foaming to the shore, but Théoden could not be overtaken.
Fey he seemed, or the battle-fury of his fathers ran like new fire in his veins, and he was borne up on Snowmane like a god of old, even as Oromë the Great in the battle of the Valar when the word was young.
His golden shield was uncovered, and lo!
it shone like an image of the Sun, and the grass flamed into green about the white feet of his steed.
For morning came, morning and a wind from the sea; and the darkness was removed, and the hosts of Morder wailed, and terror took them, and they fled, and died, and the hoofs of wrath rode over them.
And then all the host of Rohan burst into song, and they sang as they slew, for the joy of battle was over them, and the sound of their singing was fair and terrible came even to the City.

   ---J.R.R Tolkien, /The Return of the King/, chapter 5, "The Ride of the Rohirrim".
#+end_quote

#+begin_verse
Arise, arise, Riders of Théoden!
Fell deeds awake: fire and slaughter!
spear shall be shaken, shield shall be splintered,
a sword-day, a red day, ere the sun rises!
Ride now, ride now! Ride to Gondor!

Ride now, ride now! Ride to Gondor!
#+end_verse

* old notes
School system.
homework, control.
Make a fuzz.
Get mad.
Motivation.
Lack of agency.
** ?
Engineering
SO SLOW

Programming
SO MUCH HASSLE

prometheus didn't sacrifice himself to give us fire---so that we could use fire /for this/.

FIRE!

- composition
- feedback cycle
- power
** composition, feedback cycle, power
** I WANT TO FEEL THE FLAMES AND ALMOST GET BURNED
