:PROPERTIES:
:ID: ada033c3-e631-49c9-8153-b9f1c69fd31d
:END:
#+TITLE: prompts for learning

[[file:..][..]]

Sometimes we need a nudge to keep on learning, and not get stuck.
I'll share a specific approach to make that happen.

*Motivation*.
Why do we want to do this?
To "learn" is one reason.
But there are three deeper reasons:

1. To build a trust-based mentoring relationship.
2. To exercise [[id:efbb9f44-9a8e-436e-bf68-ff19d5bd990c][growth mindset]].
3. To exercise [[id:5fd923f9-dc43-4a82-ac59-8785e98bc901][coachability]].

Learning is good.
But permanently boosting your learning speed is even better!
Let's make that happen.

*Process*.
Follow these steps:

1. Find someone you trust
2. Write three or six answers, your choice
3. Share the answers with the person you trust

Then make sure you do this /again/.
Try starting with once a month.
That's it!

*Prompts to build awareness*:

1. What's one example of something you think is hard?
2. What do you want to learn?
3. What's something you're good at?

*Hard mode prompts: build awareness /and/ execute*:

1. What's one example of something you think is hard?
   a. Can you give one example of a person around you that finds this less hard?
2. What do you want to learn?
   a. Can you give one example of an activity that can help you learn that thing?
3. What's something you're good at?
   a. Do you see anyone around you that needs your help with that?

*Now, do it!*
What's hard?
What you do want to learn?
What are you good at?
Write those down and send to a friend!

#+begin_src





#+end_src

-----

#+begin_src






#+end_src

*Eating my own dogfood*.
Avoiding hard mode for now.

1. What's one example of something you think is hard?
   1. Running Datomic in prod.
      How to connect to it, how to run migrations, how to configure the underlying data store.
      I've never done that successfully before.
      I tried once and failed.
      At that time, I tried Datomic Cloud, but had never used AWS.
2. What do you want to learn?
   1. Writing apps with [[id:3dd2e3a3-ecf6-41b2-b31f-6a09b9940ef4][Electric Clojure]] and Datomic.
3. What's something you're good at?
   1. I'd like to think I'm decently good at being honest with myself about the things I don't know.
      But at the same time, I feel like that can rub some people off the wrong way, that it's too impolite, too direct.

Note: you don't have to share your answers in public.
Share with someone you trust first!
Learning is not meant to be maximally scare or maximally hard.
The people you trust tend to care about you too.
You don't have to go alone!
