#+title: My public journal

[[./..][..]]

Q: Hey! Should I read this?

A: Perhaps not. Perhaps. I use this page as a low-filter, low-threshold way to
get ideas out. Capture ideas, not process them. The reading experience might
feel like a stream-of-consciousness endeavor --- with less flow, less feelings,
less poetic content. In other words, messy, without the good sides of messy.
Still, I choose to make this public, because I believe public should be the
norm, not the exception.

🐉


* 2022-06-23
** On product and indirection.
I feel shackled by pressure for specificity.
Always be specific.
Specific is better.
Don't be vague.

Specificity expels indirection.
Indirection is core to design.

If we lazer-focus on the specific, we'll ignore problems with a longer feedback
cycle time than some arbitrary limit.
** Emacs ⟂ Product
Statement: "don't build something for yourself -- you'll ignore users"

Response: "no -- DO build product for yourself -- but design in the flexibility as indirection.
Don't force your users into your workflow.
Doing it for yourself is not workflow design - it's capability design."

By building in flexibility --- indirection --- at the right layer, we decouple the product, and give ourselves leverage.
** On fun
I'm better when I have fun.

I have fun when I build stuff for myself /and/ others.

∴ I should build stuff for myself.
