#+title: My public journal

[[./..][..]]

Q: Hey! Should I read this?

A: Perhaps not. Perhaps. I use this page as a low-filter, low-threshold way to
get ideas out. Capture ideas, not process them. The reading experience might
feel like a stream-of-consciousness endeavor --- with less flow, less feelings,
less poetic content. In other words, messy, without the good sides of messy.
Still, I choose to make this public, because I believe public should be the
norm, not the exception.

🐉


* 2022-06-23
** On product and indirection.
I feel shackled by pressure for specificity.
Always be specific.
Specific is better.
Don't be vague.

Specificity expels indirection.
Indirection is core to design.

If we lazer-focus on the specific, we'll ignore problems with a longer feedback
cycle time than some arbitrary limit.
** Emacs ⟂ Product
Statement: "don't build something for yourself -- you'll ignore users"

Response: "no -- DO build product for yourself -- but design in the flexibility as indirection.
Don't force your users into your workflow.
Doing it for yourself is not workflow design - it's capability design."

By building in flexibility --- indirection --- at the right layer, we decouple the product, and give ourselves leverage.
** On fun
I'm better when I have fun.

I have fun when I build stuff for myself /and/ others.

∴ I should build stuff for myself.
** Fully integrated feedback loops
Commonly discussed feedback loops:

1. Cycle time for recompilation
2. Cycle time for running the tests
3. Cycle time for a deploy

Uncommonly discussed feedback loops:

1. Idea-to-sharable-paper
2. Idea-to-team

* 2022-06-24
** Pandoc code blocks
(moved from separate page)

We explore how Pandoc supports embedded code.

We can write Clojure:

#+begin_src clojure
(defn act [& commands]
  ;; code
  )
#+end_src

Or Python:

#+begin_src python
def act(*commands):
    # code
    pass
#+end_src

Or even javascript:

#+begin_src javascript
function act(commands...) {
    // code
}
#+end_src
* 2022-06-25
Another morning.
** I want trailing whitespace.
Possible solutions:

1. Find org-mode native solution
2. Lol, I can just use a big verse.
   Problem solved.
   See the bottom of this file.


#+begin_verse




















#+end_verse

I like trailing whitespace - so that I can center content vertically when
writing, and avoid it moving around :)
