:PROPERTIES:
:ID: 529da36c-168f-4698-866f-bba64a5c13c5
:END:
#+TITLE: Tillit, kvalitet og intensjon i praksis: en håndbok for produkt- og programvareutvikling

[[file:..][..]]

* Til programvareutviklere som jobber i produktteam
Jobber du med programvareutvikling i et produktteam?
Dette dokumentet er til deg.

Lenge følte jeg at jeg ikke /ante/ hvordan man burde jobbe sammen når man lager produkter.
Jeg startet med en teknisk utdannelse og en teknisk jobb.
Jeg lærte meg hvordan /jeg/ kunne løse problemer /alene/.

Etter hvert slo virkelighetsbildet mitt sprekker.

- Jeg visste ikke hva jeg burde gjøre når målet ikke var sylskarpt.
- Jeg tok ikke stilling til hvordan jeg kunne gjøre andre bedre.
- Jeg observerte tilfeller der jeg trodde jeg visste nøyaktig hva som burde gjøres, og i ettertid innså at jeg hadde tatt fullstendig feil.

Disse erfaringene har ført til at jeg gjør enkelte ting annerledes enn før.
Jeg har andre forventninger til meg selv og til menneskene mine rundt meg.

Å skrive ned erfaringene .. eksplisitt
* Om god, trygg og klar kommunikasjon
** "non violent communication"
https://www.goodreads.com/en/book/show/71730



** Feedback i Netflix
I boka [[id:6ca15d90-a55e-4f0d-b185-a163ec2e077c][No Rules Rules]], beskriver [[id:85F235DE-A4CA-4054-AECE-EAEEC844A688][Reed Hastings]] og [[id:F84FC8DF-4EF2-4565-91B2-23376C732022][Erin Meyer]] hvordan tilbakemeldinger gis og tas i Netflix.

Jeg siterer:

#+begin_quote
*Giving Feedback*

- *Aim to assist*:
  Feedback must be given with positive intent.
  GIving feedback in order to get frustration off your chest, intentionally hurting the other person, or furthering your political agenda is not tolerated.
  Clearly explain how a specific behavior change will help you
#+end_quote

* Verdier: Tillit, kvalitet og intensjon
** Tillit
** Kvalitet
** Intensjon
** Andre
** Deg selv
* Opsjoner og opsjonalitet
* Release != Deploy != Review

Her er tre engelske ord.
Vi bruker ofte disse ordene når vi snakker om programvareutvikling, selv på norsk.

| Begrep  | Norsk begrep?  | Min definisjon                            |
|---------+----------------+-------------------------------------------|
| Deploy  |                | Få ny kode ut sammen med den "ekte" koden |
| Release |                | Starte å /kjøre/ den nye koden            |
| Review  | Kodegranskning | Noen andre ser over koden og kommenterer. |

** "alle kan lese og skrive alt"---Om kulturen på MIT og Bell labs på 70- og 80-tallet

** E-postlister og patcher: Linus Thorvalds lager et useriøst hobbyprosjekt

** Release, deploy og review i open source-prosjektene til [[id:7688bf50-5c2c-49b2-9efc-fcf21a539af4][Michiel Borkent]]

** God kodegranskning fokuserer på /grensesnitt mellom moduler/

Les mer (på engelsk): [[id:41b97354-0f9e-46c6-b234-a619b04152aa][Review the interface]]
* Teori og praksis
* Interaktiv programmering
** Observability
** Logger
** Test-dreven utvikling
** REPL-greven utvikling
* Hypotesetesting i produktutvikling
1. Lage opsjoner
2. Flytte opsjoner fra vage ideer til ekte initiativer
3. Funker det?
   For hvem?

Tillit, kvalitet og intensjon i relasjonen til de som /skal bruke/ produktet.

1. *tillit*.
   Stoler de på deg?
   Kommer de til å fortelle deg at det du har laget er dritt hvis du spør hva de mener?
   /ønsker/ de å fortelle deg om hverdagen sin, eller vil de helst få deg ut døra så de kan fortsette med det de egentlig bryr seg om å få gjort i dag?
2. *kvalitet*.
   Hva setter de pris på i hverdagen?
   Hva er for dem et godt stykke arbeid?
3. *intensjon*
   Hva /må de gjøre/ på en arbeidsdag?
   Hva starter de med, og hva slutter de med?
* Hierarkier og navnerom
* Navn, navnerom, operasjoner og typer i programvaredesign
* Feedback: bredde og responstid
