:PROPERTIES:
:ID: 842f9b9a-de98-4187-863e-3e6cf1b1814d
:END:
#+TITLE: What's a good intersection between work and play?

[[file:..][..]]

Play is dynamic, work is static.
That's how I view it.

When we play, we move in surprising ways.
Imagine a playground with a dozen eight-year-olds.
What's going to happen in half an hour?
Can you tell?
How about in ten minutes?

When we play, we let our mind wander.
We ease some constraints.

Finding a good balance between work and play is important.
I see it as a design challenge.
I touched on this in 2018 as [[id:c62978a1-8081-4d44-9af4-93327f387085][Static-dynamic interaction]], and frankly, I can't get the topic out of my head.
It's stuck.
When I least expect it, it jumps back at me with a "pikaboo".

Play alone is not enough.
Just work will suck all air out of an initiative.
We need both work and play, and we need a balance.

I've been enjoying [[id:e33962d6-d5cb-4ef8-b7be-9d4a537edbec][Metamuse (podcast)]] lately.
Today I was listening to Episode 27: [[https://museapp.com/podcast/27-playful-software/][Playful software with Rasmus Andersson]].
I had to stop listening when I heard this (edited for brevity):

#+begin_quote
Rasmus:

What boundaries do we need to define?
Let's say we have a couple of smart, interesting, playful people.
The company people recognize that, and say:

"Hey Lisa and Robin, would you be interested in sitting in this corner just coming up with crazy shit?
Maybe we'll ship it."

I think in most cases, that's a failure.

Maybe the constraints are way too vague.
Similar to an art class.
Ask someone to paint /anything they want/, and you get paralysis.
#+end_quote

Much can go wrong when the interaction between work and play is accidental.
Here are some examples:

| situation                                 | example failure                                                               |
|-------------------------------------------+-------------------------------------------------------------------------------|
| a group of people are only playing        | their play never helps us ship anything                                       |
| one person is playing, another is working | horrible experience for the worker. "I'm not your Nanny, I've got shit to do" |
| a group of people are only working        | no creativity at work.                                                        |

I've worked on [[id:a91a46da-75f0-4a1c-8cde-5e51ad199026][Unicad]] in its current shape for about two years.
We've seen lots of traction and I greatly enjoy working with my co-founder, so my go-to answer to "how's it going?" is "I couldn't be more happy".
But lately, something has been bugging me.

We have three major work streams right now:

| stream    | what                                                         |
|-----------+--------------------------------------------------------------|
| usability | is the product ergonomic in daily use?                       |
| sales     | are more people interested in the current value proposition? |
| value     | are we able to handle more valuable workflows?               |

For the last six months, we've been solely focused on usability.
I've taken a something of a technical product manager domain expert sales person role.
Because my co-founder is /very/ strong technically.

But where's the play?
I like coding because it's playful.
Call it a hunch.
Lack of play limits creativity.

# ?????
#
# loosing flow here.

At least I've been reasonable.

I've taken care of usability and sales.
Mostly practicalities.
But the high risk high reward value work?
That's been on hold.

-----

So, where's the actionable insight?
Are you just rambling, Teodor ...

This is where "work" asks us to be specific.
Perhaps because [[id:31478ab4-b7bf-4c87-8dae-8adb66690571][Utility is Contextual]]?
Perhaps work is to provide utility in a context.

#+begin_export html
<span style="font-size: 90pt">
🤔🧌
</span>
#+end_export

Parting words:

- Only work kills motivation and creativity
- Only play disconnects you from reality
- I think there's a correlation between propensity to treat work as play and being a strong contributor at work
- I think everyone deserves a bit of play, and /also/ deserves the responsibility to do proper work.

Does that make sense?
Perhaps?

Have a good one,

Teodor

-----

*Appendix A: a table of work and play*. (2022-09-21)

|            | *Not play*                       | *Play*                                          |
| *Not work* | Meaningless paper pushing & toil | We had fun last week but it doesn't help us now |
| *Work*     | I'm a cog in a system            | Deliverable plus autonomy                       |

*Appendix B: Proposed definitions for /work/ and /play/*

*play is unpredictable*.
When we play, we can't predict where we will end up in advance.
That's where the excitement comes from :)

*when we work, there is a deliverable*.
Effective people know how to anchor their efforts so their effort add value in a context.
And they keep that context in mind during the work, not as an afterthought.
See [[id:31478ab4-b7bf-4c87-8dae-8adb66690571][Utility is Contextual]] and [[id:9f52d562-4a06-4ea1-a461-2018fca5baf1][There's always a deliverable]].

I also think it's possible to orient a product team around /both/ work and play.
Early draft for a work process: [[id:7e70b878-1ef2-4ab6-885b-727eb557213d][OGGPOW: A non-coercive strategic framework]].

*Appendix C: programming as play*

Oddmund kindly suggested I look into [[https://austinhenley.com/blog/programmingasplay.html][Programming as play]].

The author, Austin Z. Henley refers further to an academic paper: [[https://static.barik.net/barik/publications/vlhcc2017/PID4950171.pdf][Expressions on the Nature and Significance of Programming and Play]]

#+BEGIN_VERSE




#+END_VERSE
