:PROPERTIES:
:ID: 842f9b9a-de98-4187-863e-3e6cf1b1814d
:END:
#+TITLE: What's a good intersection between work and play?

[[file:..][..]]

Play is dynamic, work is static.
That's how I view it.
When we play, we move in unsurprising ways.
Imagine a playground where a dozen eight-year-olds are playing.
Are you able to predict what's going to happen in half an hour?
Even in ten minutes?

When we play, we let our mind wander.
We ease some constraints.

I believe the act of designing the boundary between work and play is tremendously important.
I wrote about this as [[id:c62978a1-8081-4d44-9af4-93327f387085][Static-dynamic interaction]] in 2018, and I can't get the topic out of my mind.
Play alone does not suffice.
Work alone does not suffice.
We need both, and they must be balanced.

I've been enjoying [[id:e33962d6-d5cb-4ef8-b7be-9d4a537edbec][Metamuse (podcast)]] lately.
Today I was listening to Episode 27: [[https://museapp.com/podcast/27-playful-software/][Playful software with Rasmus Andersson]].
I had to stop listening when I heard this (somewhat edited by me for brevity):

#+begin_quote
Rasmus:

What boundaries do we need to define?
Let's say we have a couple of smart, interesting, playful people.
The company people recognize that, and say:

"Hey Lisa and Robin, would you be interested in sitting in this corner just coming up with crazy shit?
Maybe we'll ship it."

I think in most cases, that's a failure.

Maybe the constraints are way too vague.
Similar to an art class.
Ask someone to paint /anything they want/, and you get paralysis.
#+end_quote

But there are plenty of things that can go wrong when the line between work and play is drawn without care.

| situation                                 | example failure                                                               |
|-------------------------------------------+-------------------------------------------------------------------------------|
| a group of people are only playing        | their play never helps us ship anything                                       |
| one person is playing, another is working | horrible experience for the worker. "I'm not your Nanny, I've got shit to do" |
| a group of people are only working        | no creativity at work.                                                        |

I've worked on [[id:a91a46da-75f0-4a1c-8cde-5e51ad199026][Unicad]] in its current shape for about two years.
We've seen lots of traction and I enjoy working with my co-founder, so my general answer to "how's it going?" is "I couldn't be more happy".
But lately, something has been bugging me.

We have three major work streams:

| stream    | what                                                         |
|-----------+--------------------------------------------------------------|
| usability | is the product ergonomic in daily use?                       |
| sales     | are more people interested in the current value proposition? |
| value     | are we able to handle more valuable workflows?               |

For the last six months, we've been solely focused on usability.
I've taken a somewhat technical product manager domain expert sales person role.
Because my co-founder is /very/ strong technically.

But where's the play?
I like coding because it's playful.

Back to reasonability.

So I've been taking care of usability and sales.
Mostly practical stuff.
But the high risk high reward value work has been dormant.

-----

#+BEGIN_VERSE














#+END_VERSE
