:PROPERTIES:
:ID: 2be96e32-2649-4416-956a-64cbb23a3f9e
:END:
#+TITLE: tech learning ladder

[[file:..][..]]

Timestamp: 2023-05-01

As a tech person, what might one learn?

I find that to be a hard question.
Our industry is moving.
Our tools are changing.
And as we get better, we gain agility.
We don't slow down, we speed up.

So I'm hesitant to leave this document as /the answer for forever/.
I'll strive for [[id:dfd45cfa-3154-47ef-8f74-06fe0e69715e][lindy compatibility]] where possible, but not at the expense of clarity.

-----

Here we go.
In a mix of Norwegian and English, sorry.

- HTTP og servere
  - Hva er en HTTP-request?
  - Headere
    - Accept
    - Content-Type
  - Body
  - HTTP-request med Curl
  - HTTP-request med js-fetch
  - Inspisere HTTP-requests i Firefox / Chrome
- Testing og andre teknikker for å vite om koden gjør den du tror den gjør
  - Enhetstester
  - Integrasjonstester
  - Hvordan kjører testene i CI?
  - ---
  - Property testing
- Utviklingsprosess.
  - Hvordan spille andre gode.
    - Jeg er fersk, og jobber sammen med en erfaren utvikler.
      Hvordan kan jeg hjelpe grinebiteren å ha færre problemer i hverdagen?
    - Jeg er erfaren utvikler.
      Hvordan kan jeg hjelpe en nyansatt å gjøre en god jobb?
  - Parprogrammering
  - PR-er
    - hvorfor+hvordan bruker vi PR-er i dette teamet?
      - unngå bugs?
      - lære / lære bort?
    - Hvor stor PR er dette?
      - Gjør du én ting eller mange ting?
      - Hvordan skrive kode for å kunne shippe mindre inkrementer.
    - er det mulig å skjønne hva du har gjort?
      - klarer du å uttrykke det konsist?
      - bør du inkludere bilder, figurer eventuelt en video?
        Github støtter opplasting av media rett i PR-beskrivelse.
    - hva ønsker du feedback på?
  - ---
  - Feature-flagging
  - Ensemble-programmering
  - Gradvis utrulling
- Databaser og datamodellering
  - Get started with PostgreSQL
  - Migrations
  - Putting "non-obvious" stuff in the database
    - Assets
    - Cached things
  - /one database/ vs "We have PostgreSQL, Redis and an object store and we don't know where to put things"
- CSS
  - Hva er en anbefalt måte å begynne å skrive CSS på?
- React
  - Hvordan går jeg fra
- Sikkerhet
  - Marcus shortlist
    - «Tokens»: https://paseto.io/
    - «Kryptering»: https://doc.libsodium.org/
    - «Passordhashing»: https://en.wikipedia.org/wiki/Argon2?wprov=sfti1
    - Neither of those three? Reconsider your approach.
    - Ensure you test your stuff /extensively/.
- Unix og Unix-verktøy
  - Git
  - The shell
  - Curl
  - Environment variables
  - Command line arguments

That's all for level 1.
Topics that can be postponed are put below the "fold" (the horizontal line)

-----

- Interfaces, contracts and API design
  - Interfaces between modules
  - Typed interfaces in programming languages
    - Go: =interface=
    - Java: =interface=
    - Typescript: =interface=
    - Rust: =trait=
    - Haskell: =class= (typeclass)
    - Clojure: =protocol= (java =interface= also supported)
  - CQRS and event sourccing
  - Idempotence
  - Immutability
  - Teodor opinion /prefer shallow hierarchies/
    - build namespaces, not taxonomies.
  - Data and serialization.
    Cycles.
- Functional programming.
  - Types.
  - Data.
  - Pure functions.
  - System-level functional programming (eg using GET requests with immutability and caching)
- Types and type systems.
  - Types in object oriented languages
    - Go
    - Typescript
  - Types in functional languages
    - Elm
    - Haskell
    - Clojure
    - Elixir
    - F#
- Declarative programming
  - HTML
    - HTMX (https://htmx.org/)
  - SQL
  - Prolog
  - Minikanren
  - Datalog
