:PROPERTIES:
:ID: 12fea9ba-c435-4158-ae33-d9fc9fa45a44
:END:
#+TITLE: Kreativitet til salgs

[[file:..][..]]

kreativitet ⟷ salg

Kreativitet til salgs.
Det er forretningsmodellen til Iterate.

#+begin_quote
Someone once asked Somerset Maugham if he wrone on a schedule, or only when struck by inspiration.
"I only write when inspiration strikes", he replied.
"Fortunately, it strikes every morning at nine o'clock sharp."

— [[id:c24fb740-235f-4798-aee6-a3075a45fef6][Steven Pressfield]], [[id:fa08845b-32ed-4e74-a458-de85884da52d][The War of Art]]
#+end_quote

Vi lager en ting, så er folk misfornøyd.
Kunden er misfornøyd.
Sluttbrukeren er misfornøyd.
Designeren er misfornøyd.
Den andre utvikleren sier "dette kunne du gjort helt annerledes og mye bedre" lenge etter at du er fardig.
Noen blir fly forbanna, og kjefter.
Kjefter på deg, kjefter på jobben du har gjort.
Du ble ferdig, og det var vanskelig å få til.
Du har gjort ditt beste.

Noen ganger må vi ha tykk hud.

Neste dag klokker vi inn på nytt om morgenen.
Vi lover oss lev å få gjort en fornuftig ting før lunsj, og en fornuftig ting etter lunsj.
Vi tar en kaffe med utvikleren vi jobber med, og ler av hvor mange bugs vi har.

Utvikling er vanskelig.
Alikevel har vi valgt å jobbe som utviklere fordi vi liker å lære, liker å utforske, og liker å kunne lage verktøyene vi bruker.

Vi fortsetter.
Dag ut, dag inn.
/Ekstremt sakte/ blir ting litt og litt bedre.
Vi har faktisk færre problemer med kunden enn vi hadde før.
Vi skjønner mer av hva kunden trenger, og vi er mer komfortable med hva vi får til, og hva vi ikke får til.

Jobben vår er å selge kreativitet.

Vi deler ikke arbeidet vårt fordi vi er så ekstremt stolte.
Eller fordi vi mener at arbeidet vårt er så ekstremt bra.
Vi deler arbeidet vårt fordi vi er profesjonelle.
Og når jobben er gjort, slipper vi arbeidet ut i verden.

*appendix*

| kreativitet | salg              |
| individ     | kollektiv         |
| tekstur     | glatthet          |
| fantasi     | objekter i verden |
| framtid     | nåtid             |

trust can bridge the gap.
but you can safely [[id:79d9c6f5-7be4-4f4e-b418-321c12e8c39f][defer the trust problem]] for some time.
then you must face it.
If you don't, you stay in Neverland and risk never growing up.

| transcendence | facticity | [[id:40629ca8-68df-40e9-a40c-33460b683df8][Simone de Beauvoir]]        |
| teori         | praksis   | [[id:369abfa2-8b8c-4540-958f-d0fce79f132b][David Deutsch]], Yogi Berra |

#+begin_quote
Man must not attempt to dispel the ambiguity of his being but, on the contrary, accept the task of realizing it.

— [[id:40629ca8-68df-40e9-a40c-33460b683df8][Simone de Beauvoir]], [[id:63ee3837-fb0e-43c9-81fd-1f0b5b2c7bd6][The Ethics of Ambiguity]]
#+end_quote

#+begin_quote
sitat david deutsch

— [[id:369abfa2-8b8c-4540-958f-d0fce79f132b][David Deutsch]], [[id:dde82bbc-e4c8-49c0-b577-dba0cba0bdf7][The Beginning of Infinity]]
#+end_quote

#+begin_quote
In theory there is no difference between theory and practice. In practice, there is.

— Yogi Berra
#+end_quote
