:PROPERTIES:
:ID: 12fea9ba-c435-4158-ae33-d9fc9fa45a44
:END:
#+TITLE: Kreativitet til salgs

[[file:..][..]]

kreativitet ⟷ salg

#+begin_quote
Someone once asked Somerset Maugham if he wrone on a schedule, or only when struck by inspiration.
"I only write when inspiration strikes", he replied.
"Fortunately, it strikes every morning at nine o'clock sharp."

— [[id:c24fb740-235f-4798-aee6-a3075a45fef6][Steven Pressfield]], [[id:fa08845b-32ed-4e74-a458-de85884da52d][The War of Art]]
#+end_quote

| individ | kollektiv         |
| tekstur | glatthet          |
| fantasi | objekter i verden |
| framtid | nåtid             |

trust can bridge the gap.
but you can safely [[id:79d9c6f5-7be4-4f4e-b418-321c12e8c39f][defer the trust problem]].
for some time.
then you must face it.
If you don't, you stay in Neverland and risk never growing up.

| transcendence | facticity | Simone de Beauvoir |
| teori         | praksis   | David Deutsch      |

#+begin_quote
Man must not attempt to dispel the ambiguity of his being but, on the contrary, accept the task of realizing it.

- [[id:40629ca8-68df-40e9-a40c-33460b683df8][Simone de Beauvoir]], [[id:63ee3837-fb0e-43c9-81fd-1f0b5b2c7bd6][The Ethics of Ambiguity]]
#+end_quote

#+begin_quote
sitat david deutsch
#+end_quote
