:PROPERTIES:
:ID: 276c7103-9366-4326-8cfd-3c0871be3c64
:END:
#+title: Strong relations

[[./..][..]]

DRAFT

Closely related groups are densely linked with strong relationships.
"Densely linked": there are many links.
"strong relationships": each link is heavy, carries trust both ways.

Deep knowledge of a subject is not knowing all the five line dictionary definitions --- it is being able to navigate the field from node to node, knowing what relates to what.

From /Aphorisms/:

#+begin_quote
5 - Never link to content without enriching the intent of linking with context.
#+end_quote

* I feel like play.teod.eu is too fragmented
Too hard to connect ideas.
Too hard to navigate between ideas.
Too hard to see the whole picture. The composition of ideas.

Visa is using maps for this.

Simon Wardley is using maps for this.

Designers are using Figma to connect stuff.

(and I can't even link to Simon Wardley or Visa because I don't have a system for strong links)

Do I want an entity system?

🤔
* How can stuff be more connected?
By making it possible / nice to link between pages

By making some small "hover over this" things, or footnotes, or something like that

By becoming better at publishing not just plain text, but diagrams, figures, you name it.
* How can stuff be more connected --- specifically, what can I do?
I could write an article where I use Remarkable drawings actively.

I could use Figma / Miro to illustrate stuff.

I could create static.teod.eu so that "putting up an artifact" is separate from reusing it.

I could create an example of a "fat link" / "rich reference" / "strong relation"
* Do I want to use some other kind of system as a "reference provider"?
I could externalize this.

Miro. Roam.

Export relations somehow.
Make the relations rich, imbue them with context.
Entity type for "map".

Hmm.

But how would I use this?
That's the question.

Or just list forward references / back references in the end.
That could give a nice interactive experience.

#+begin_src clojure
{:forward {"thinkwert" {,,,}
           "visa" {,,,}}
 :back {"swardley" {,,,}
        "figma" {,,,}}}
#+end_src
* I'm curious about the crossover between strong relations and trust
Is it the same?

Noo ... "strong relations" is more vague, context independent.
Trust is a specific type of relation.
And it /can be strong/.
But is trust the most important type of relation?
* In communities, look for strong centers
Wat?

If you want to contribute to open source, look for projects that are actively used, and actively maintained.

Why?

Well ...

Hmm.
* Expert-level skill is characterized by strong relations
Why?

Expert level skill is measured by effectiveness.
Effectiveness requires effective execution and effective communication.

Effective communication is
  deep language knowledge
  and effective use of language.

Effective use of language requires that each word /hits hard/.
A hard-hitting word is a strong relation.

-----

* random / dump / review

Strong relations between people.
