#!/usr/bin/env bb

(ns bb-install
  (:require [babashka.cli :as cli]
            [babashka.fs :as fs]
            [clojure.string :as str]
            [clojure.java.shell]))


;; $ bb -m bb-install bb.edn --main ucad --install-dir ~/.local/bin --dry-run
;; #!/usr/bin/env bash
;;
;; # This script was generated by `bb install`.
;; # TODO link to `bb install` docs
;;
;; exec bb --config /home/teodorlu/dev/iterate/squirreltime/ucad/bb.edn -m ucad "$@"

(defn- lines [& ls]
  (str/join "\n" (map str ls)))

(defn shell-escape-string [s]
  ;; TODO, not sure how
  ;; Otherwise, we'll fail on spaces in file names
  s)

(defn run [opts]
  (let [opts (merge {:wrapper-script-type :bash                    ; :wrapper-script-type should default to batch on Windows
                     :install-dir (fs/expand-home "~/.local/bin")}
                    opts)
        {:keys [dry-run main wrapper-script-type install-dir bb-edn-path]} opts]
    ;; (assert dry-run "Only dry-run is supported for now")
    (assert main)
    (assert wrapper-script-type)
    (assert (#{:bash} wrapper-script-type) "Only bash wrappers are supported for now")
    (assert install-dir)
    (assert bb-edn-path)

    (let [script (lines "#!/usr/bin/env bash"
                        ""
                        "# This script was generated by `bb install`."
                        "# TODO link to `bb install` docs"
                        ""
                        (str "exec bb --config " (shell-escape-string (fs/absolutize bb-edn-path)) " -m " main " \"$@\"")
                        "")
          script-path (str install-dir "/" main)]
      #_
      (prn
      ;; for debugging
       {:script-path script-path
        :install-dir install-dir
        :bb-edn-path bb-edn-path
        :test (str (fs/canonicalize "./lol.txt"))})
      (if dry-run
        (println script)
        (do
          (spit script-path script)
          ;; fs executable?
          (clojure.java.shell/sh "chmod" "+x" (str (fs/canonicalize script-path)))
          nil)))))

(defn -main [& args]
  (let [opts (cli/parse-opts args
                             {:alias {:m :main}
                              :coerce {:main :string
                                       :wrapper-script-type :keyword
                                       :dry-run :boolean
                                       :install-dir :string}
                              :args->opts [:bb-edn-path]})]
    (run opts)))

;; Not sure what the equivalent of python's "run the main if this file is run as a main"
;;
;; So hack:

(apply -main *command-line-args*)
